import type { DocPage } from "../pages";

/**
 * Part I - Foundations
 *
 * Import this into `content/docs/pages.ts` and merge into `docPages`.
 */
export const part01FoundationsPages: DocPage[] = [
  {
    slug: ["foundations", "from-prompt-to-production"],
    title: "Chapter 1 - From Prompt to Production",
    description:
      "A production mental model for shipping LLM features: architecture, tradeoffs, failure modes, and the improvement loop.",
    group: "Part I: Foundations",
    toc: [
      "What You Will Learn",
      "1.1 The Lifecycle of an AI Request",
      "1.2 Components of Modern AI Systems",
      "1.3 Core Engineering Tradeoffs",
      "1.4 Why Prompt Engineering Isn't Enough",
      "Common Mistakes and Debugging Habits",
      "Exercises",
      "Chapter Summary",
    ],
    body: [
      "# Chapter 1 - From Prompt to Production",
      "",
      "Shipping an LLM feature is not the same as writing a clever prompt. A prompt can be the first useful sketch of a behavior, but a production system has to survive messy users, unclear intent, private data, slow dependencies, malformed outputs, cost pressure, and product expectations. The model is important, but it is not the whole product.",
      "",
      "The simplest beginner diagram is user input, then model, then response. That diagram is not wrong; it is just too small. It hides all the decisions that make an AI application reliable. Before the model sees anything, the application has to decide what the user is trying to do, what context belongs in the request, what tools are safe to expose, and what budget the request is allowed to spend. After the model responds, the application has to validate, format, observe, and evaluate the result.",
      "",
      "This chapter builds the mental model for the rest of the handbook. We will follow one request from the moment a user expresses intent to the moment the system learns from production behavior. The goal is not to memorize a list of components. The goal is to see why those components exist.",
      "",
      "## What You Will Learn",
      "",
      "By the end of this chapter, you should be able to explain an AI request as a full product workflow rather than a single model call. You should be able to describe where context comes from, why tools need validation, why latency and cost are design constraints, and why production systems need traces and evaluations. You should also understand why prompt engineering matters, but cannot carry the whole system by itself.",
      "",
      "## 1.1 The Lifecycle of an AI Request",
      "",
      "A user message begins as intent. When someone writes, 'My invoice shows double charged shipping. Can you fix it?', they are not asking for generic text about invoices. They are asking the product to understand a billing situation, inspect relevant records, obey company policy, possibly use a tool, and explain the result clearly. The text is only the surface. The intent is the thing the system must serve.",
      "",
      "The first major step is workflow selection. A chat interface can make every interaction look like a conversation, but the backend still has to choose a workflow. Some requests are simple question answering. Some require retrieval from documents. Some require structured extraction. Some require tool calls. Some require multi-step planning. The workflow determines what context is needed and what risks must be controlled.",
      "",
      "Once the workflow is chosen, the system builds context. Context is the model's working memory for this request. It may include system instructions, product policy, relevant conversation history, retrieved documents, account data, tool descriptions, and formatting expectations. A beginner often thinks context means 'the prompt.' In production, context is a carefully assembled bundle of evidence and constraints.",
      "",
      "Context must also be selective. Long context is not free. Every extra token can increase latency, raise cost, and distract the model. A strong context builder does not dump everything into the request. It chooses what matters, compresses what can be summarized, removes stale information, and keeps the model focused on the current task.",
      "",
      "After context is assembled, the model runtime performs inference. The model reads the input tokens during the prefill phase, then generates output during the decode phase, one token at a time. Streaming can make this feel immediate to the user, but generation is still sequential under the hood. This matters because output length affects latency and cost directly.",
      "",
      "The model's output is not automatically a finished product response. It may need parsing, schema validation, citation checks, redaction, safety review, or formatting. If the model requested a tool call, the system must validate the tool name and arguments before execution. If the tool returns private or sensitive data, the final answer must include only what the user is allowed to see.",
      "",
      "The lifecycle does not end when the answer is returned. A production system records what happened. It stores a request id, model settings, prompt version, retrieval results, tool calls, latency, token counts, costs, errors, and validation outcomes. Later, evaluation uses those records to decide whether the system is improving or regressing.",
      "",
      "A useful way to remember the lifecycle is: intent becomes workflow, workflow determines context, context goes to the model, the model may use tools, the output is checked, the response is delivered, and the system learns from the trace.",
      "",
      "## 1.2 Components of Modern AI Systems",
      "",
      "The user interface is where intent enters the system. It can be a chat box, command palette, form, voice interface, editor action, or background automation. Good AI interfaces do more than collect text. They set expectations, show progress, support cancellation, and make uncertainty visible.",
      "",
      "The API boundary authenticates the request and applies basic controls such as rate limits, tenant limits, and request size limits. This layer may feel boring compared with the model, but it is where production discipline begins. If the boundary accepts unlimited requests and unlimited context, the rest of the system will eventually fail under load or abuse.",
      "",
      "The orchestrator is the workflow brain. It decides which steps happen and in what order. For a simple feature, the orchestrator may only build context and call the model once. For a support assistant, it may retrieve documents, ask the model whether a tool is needed, call the tool, feed the result back to the model, and then validate the final answer. The orchestrator is where retries, timeouts, budgets, and termination conditions live.",
      "",
      "The context builder is responsible for creating the model input. It chooses instructions, history, retrieved knowledge, tool schemas, memory, and user-specific data. This is one of the most important parts of an AI application because the model can only reason with what it sees. Bad context produces bad answers even when the model is strong.",
      "",
      "Retrieval systems give the model access to external knowledge. They might search product documentation, policy databases, tickets, source code, or customer records. Retrieval is powerful because it lets the system answer with fresh and domain-specific information, but it introduces its own failure modes. Retrieved content can be stale, irrelevant, duplicated, or unsafe to trust without filtering.",
      "",
      "Tool execution connects language to software. This is where a model can look up an invoice, create a ticket, search a repository, or update a record. Tool execution must be treated as a security boundary. The model can propose an action, but the application decides whether that action is valid, authorized, idempotent, and safe.",
      "",
      "The model runtime is where token generation happens. The runtime may be an external API, a self-hosted inference server, or a routing layer across several models. Engineering choices here affect latency, cost, throughput, context length, streaming behavior, and reliability.",
      "",
      "Post-processing turns model output into product output. Sometimes this means rendering Markdown. Sometimes it means validating JSON. Sometimes it means repairing a malformed response, removing sensitive data, attaching citations, or refusing to act. Post-processing is the difference between text that sounds plausible and output that software can safely use.",
      "",
      "Observability records the system's behavior. In traditional software, logs and traces help answer what happened. In AI systems, they are even more important because failures are often semantic rather than obvious crashes. The system may return a 200 response and still be wrong. Traces, token metrics, prompt versions, retrieval metadata, and sampled outputs make these failures diagnosable.",
      "",
      "Evaluation measures whether the system works. A team needs golden datasets, regression tests, human review, rubric-based scoring, and sometimes model-assisted judging. Without evaluation, every prompt change becomes a guess. With evaluation, the team can ask whether a change improved groundedness, reduced hallucination, lowered cost, or introduced a new failure mode.",
      "",
      "## 1.3 Core Engineering Tradeoffs",
      "",
      "Every AI feature is shaped by tradeoffs. Latency, cost, quality, reliability, and scalability pull against each other. Improving one often stresses another. The job of an engineer is not to maximize everything at once. The job is to choose the right balance for the product and make the choice visible.",
      "",
      "Latency is the time the user waits. It includes queueing, retrieval, tool calls, prefill, decode, post-processing, and network overhead. A system can feel slow even when the model is fast if retrieval or tools are blocking the response. Streaming can improve perceived latency, but it does not remove the need to control total work.",
      "",
      "Cost is driven by tokens, model choice, tool calls, retries, and workflow length. A beautiful answer that costs too much per request may not be shippable. Cost engineering is not about making the system cheap at all costs. It is about making the economics predictable enough for the product to survive.",
      "",
      "Quality means the response is useful, correct, grounded, and appropriate for the user's goal. Quality often improves when you add better context, stronger models, retrieval, tool use, or validation. But each addition has a price. More context can distract the model. More tool calls can increase latency. Stronger models can raise cost.",
      "",
      "Reliability means the system behaves predictably under normal and abnormal conditions. AI reliability includes traditional concerns like timeouts and retries, but also semantic concerns like malformed structured output, hallucinated tool calls, stale retrieval, and infinite agent loops. Reliability comes from constraints and measurement, not hope.",
      "",
      "Scalability means the system can handle more users, larger contexts, more tenants, and more workflows without collapsing. Scaling AI systems is not only about adding servers. It is also about limiting context, batching inference, separating workloads, caching repeated work, and protecting shared resources from noisy tenants.",
      "",
      "A product team should discuss these tradeoffs explicitly. A code assistant may accept higher cost for better quality because wrong code is expensive. A high-volume support bot may prefer a smaller model plus retrieval because unit economics matter. A safety-sensitive workflow may choose slower responses if validation reduces risk. The correct answer depends on the product.",
      "",
      "## 1.4 Why Prompt Engineering Isn't Enough",
      "",
      "Prompt engineering is useful. Clear instructions, examples, formatting constraints, and well-written role guidance can improve model behavior. But prompt engineering is not a substitute for system design. A prompt cannot enforce authorization. A prompt cannot guarantee a database update is idempotent. A prompt cannot measure cost, trace latency, or prove that a new release improved quality.",
      "",
      "The limitation is simple: prompts influence behavior, while systems constrain behavior. In production, influence is not enough. You need schemas for structured output, validators for tool arguments, budgets for loops, timeouts for dependencies, permissions for private data, and evaluations for regressions.",
      "",
      "This is why modern AI engineering moves from prompt engineering to context engineering and system engineering. The prompt remains part of the system, but it is surrounded by retrieval, memory, tool contracts, observability, and evaluation. The model should receive the right information, in the right shape, at the right time, with the right guardrails.",
      "",
      "A useful test is to ask what happens when the model is wrong. If the answer is 'the user sees the wrong thing and we hope they notice,' the system is not production-ready. If the answer is 'the output fails validation, the trace records the failure, the workflow falls back safely, and the evaluation catches the regression,' then you are engineering the system rather than merely prompting it.",
      "",
      "## Common Mistakes and Debugging Habits",
      "",
      "A common beginner mistake is treating the model call as the whole application. This leads to systems that work in demos but fail in production because nobody can explain where the answer came from, why it was slow, or whether it was allowed to use the data it used.",
      "",
      "Another mistake is adding more context whenever the model fails. Sometimes the model needs more information, but often it needs better selected information. A shorter, cleaner context can outperform a long, noisy one. The question is not how much can fit in the window. The question is what should be in the model's working memory.",
      "",
      "Teams also underestimate output validation. A natural language answer can be plausible and still wrong. A JSON object can be valid and still unsafe. A tool call can be syntactically correct and still unauthorized. Validation should check the contract that matters to the product, not merely whether the text looks reasonable.",
      "",
      "The debugging habit to build early is tracing. For every important request, you want to know what context was sent, which model was used, what tools were called, how long each step took, how many tokens were consumed, and what validations passed or failed. Without this, debugging becomes guesswork.",
      "",
      "## Exercises",
      "",
      "Take an AI feature you have seen or built and describe the full request lifecycle in prose. Start with the user's intent and end with observability and evaluation. Do not stop at the model call. Explain what context is needed, what tools might be involved, and what checks should happen before the response reaches the user.",
      "",
      "Next, identify the main tradeoff for that feature. Is the product more sensitive to latency, cost, quality, reliability, or scale? Explain what you would optimize first and what risk that optimization creates.",
      "",
      "Finally, design the minimum trace you would want for debugging. Describe the fields in plain language: request identity, prompt version, model settings, retrieval sources, tool calls, timings, token counts, output checks, and error states.",
      "",
      "## Chapter Summary",
      "",
      "An AI product is not a prompt wrapped around a model. It is a system that turns user intent into a controlled workflow. The workflow builds context, calls a model, may execute tools, validates the result, returns a response, and records what happened so the team can improve it.",
      "",
      "Prompt engineering still matters, but it is only one layer. Production AI requires context engineering, tool contracts, reliability controls, observability, evaluation, and explicit tradeoff management. Once you can draw that full flow, you are thinking like an AI systems engineer."
    ].join("\n"),
  },
  {
    slug: ["foundations", "context-engineering"],
    title: "Chapter 2 - Context Engineering",
    description:
      "How to construct the right context every time: system prompts, dynamic assembly, token budgets, memory, compression, and versioning.",
    group: "Part I: Foundations",
    toc: [
      "What 'Context' Really Means",
      "2.1 Prompt Engineering vs Context Engineering",
      "2.2 Harness Engineering",
      "2.3 System Prompts",
      "2.4 Dynamic Prompt Construction",
      "2.5 Context Window Management",
      "2.6 Context Compression",
      "2.7 Conversation Memory",
      "2.8 Long-Context Strategies",
      "2.9 Prompt Templates",
      "2.10 Prompt Versioning",
      "Common Mistakes",
      "Exercises",
      "Chapter Summary",
    ],
    body: [
      "# Chapter 2 - Context Engineering",
      "",
      "If Chapter 1 taught you that shipping LLM features is systems engineering, this chapter teaches you the system component you will touch the most:",
      "",
      "> Context engineering: reliably assembling the right information and instructions for the model, within a limited budget, for each request.",
      "",
      "The model does not know what you meant. It only sees the tokens you send.",
      "So your job is to make what it sees match what you need it to do.",
      "",
      "## What 'Context' Really Means",
      "",
      "In many teams, 'prompt' means 'a big string.' In production, context is a structured bundle:",
      "",
      "```",
      "Context = Instructions + Evidence + State + Constraints + Interfaces",
      "```",
      "",
      "Where:",
      "",
      "- Instructions: what role to play, how to respond, what to avoid",
      "- Evidence: the facts to ground the answer (retrieved docs, DB rows)",
      "- State: user/account state, current document, feature flags",
      "- Constraints: output schema, safety rules, budgets",
      "- Interfaces: tool schemas, available actions, function signatures",
      "",
      "### The Context Stack (a reusable diagram)",
      "",
      "Think of context as a stack with priorities:",
      "",
      "```",
      "Highest priority",
      "  [System message]      - role, safety, global rules",
      "  [Developer message]   - product behavior, formatting rules",
      "  [Tool schemas]        - what actions exist + argument contracts",
      "  [Retrieved evidence]  - facts for grounding",
      "  [Memory summary]      - stable user preferences / long-term notes",
      "  [Conversation window] - recent turns (trimmed)",
      "  [User message]        - the actual request right now",
      "Lowest priority",
      "```",
      "",
      "Different APIs implement roles differently, but the underlying idea is stable:",
      "",
      "- Put global rules early.",
      "- Put evidence near where the model will use it.",
      "- Avoid burying critical constraints under large blocks of text.",
      "",
      "## 2.1 Prompt Engineering vs Context Engineering",
      "",
      "### Prompt engineering (narrow)",
      "",
      "You change the instruction text:",
      "",
      "- Add examples",
      "- Clarify the output format",
      "- Add do/don't rules",
      "",
      "This helps when the model already has what it needs but is behaving poorly.",
      "",
      "### Context engineering (wide)",
      "",
      "You design the inputs to prompting:",
      "",
      "- Which facts to retrieve, and how to present them",
      "- Which conversation turns to keep",
      "- How to represent state (tables, bullet points, JSON)",
      "- How to enforce output constraints (schemas, stop conditions, validators)",
      "- How to budget tokens so the important stuff always fits",
      "",
      "Context engineering helps when the model is missing key data, outputs are inconsistent, or it follows the wrong instruction because your context is confusing.",
      "",
      "### Same instruction, different outcome (evidence vs guessing)",
      "",
      "User: 'Write a refund response.'",
      "",
      "Two contexts:",
      "",
      "1. No evidence, no policy: the model will invent rules (hallucinate) because it must produce something.",
      "2. Refund policy + order details + constraints: the model behaves like a reliable system.",
      "",
      "Most hallucinations are actually 'we forgot to provide evidence.'",
      "",
      "## 2.2 Harness Engineering",
      "",
      "Harness engineering makes context construction and model calls:",
      "",
      "- Observable (you can see inputs/outputs)",
      "- Testable (you can run offline evals)",
      "- Versioned (you can roll back)",
      "",
      "### What to log (safely)",
      "",
      "At minimum, per request:",
      "",
      "- Prompt/context version ids",
      "- Model name and settings (temperature, max output tokens)",
      "- Retrieval query + ids of retrieved documents (not necessarily full content)",
      "- Tool calls (names, durations, success/failure)",
      "- Token counts (input and output)",
      "- Final outcome label when available (success/failure, parse ok, user thumbs-up, etc.)",
      "",
      "Privacy notes:",
      "",
      "- Prefer storing references (doc ids) over raw sensitive text.",
      "- If you must store text for debugging, limit retention and redact PII.",
      "",
      "### Make context reproducible",
      "",
      "The worst debugging case is when you cannot reproduce the exact context that caused a bug.",
      "",
      "Do this instead:",
      "",
      "- Keep all context-building inputs explicit (functions with clear inputs/outputs).",
      "- Avoid non-deterministic ordering (for example: iterating over object keys).",
      "- Version your templates and retrieval settings.",
      "",
      "## 2.3 System Prompts",
      "",
      "System prompts are powerful because they are always present and usually treated as high priority.",
      "They are also dangerous because they can become a dumping ground.",
      "",
      "### What belongs in a system message",
      "",
      "Good system content:",
      "",
      "- The assistant role (for example: 'You are a support agent for Acme Billing')",
      "- Hard safety constraints (for example: 'Never ask for passwords')",
      "- Universal formatting rules (markdown, short paragraphs)",
      "- Tool-usage posture (use tools for account-specific facts)",
      "",
      "Bad system content:",
      "",
      "- Long product manuals (use retrieval)",
      "- Full policy documents (retrieve and cite the relevant sections)",
      "- Per-user preferences (use memory)",
      "",
      "### A system prompt template (short, stable, enforceable)",
      "",
      "```text",
      "Role:",
      "- You are the Acme Support Assistant.",
      "",
      "Goals:",
      "- Resolve the user's issue or gather missing info.",
      "- Be accurate. Do not guess about account-specific facts.",
      "",
      "Rules:",
      "- If account data is required, request it via tools; do not invent.",
      "- If you are uncertain, ask a clarifying question.",
      "- Keep responses under 150 words unless the user asks for detail.",
      "",
      "Output:",
      "- Use markdown.",
      "- Use short headings when helpful.",
      "```",
      "",
      "Notice what is missing: long knowledge. That belongs in retrieval or tools.",
      "",
      "## 2.4 Dynamic Prompt Construction",
      "",
      "Dynamic construction means your prompt is assembled based on the request.",
      "",
      "### Why dynamic construction is necessary",
      "",
      "Different requests need different context:",
      "",
      "- Billing question needs invoice data.",
      "- 'Explain this code' needs the code snippet, not the user's last 20 turns.",
      "- 'Summarize this PDF' needs selected pages or an extracted outline.",
      "",
      "### A reliable assembly pipeline",
      "",
      "Use staged building:",
      "",
      "```",
      "1) Normalize input",
      "2) Classify intent",
      "3) Gather evidence (tools + retrieval)",
      "4) Decide budgets",
      "5) Pack context (instructions + evidence + history)",
      "6) Call model",
      "7) Validate output",
      "```",
      "",
      "### Token budgeting by section (a production habit)",
      "",
      "Instead of 'stuff everything in,' allocate budgets:",
      "",
      "```",
      "Total input budget: 10,000 tokens",
      "  - System + developer instructions: 800",
      "  - Tool schemas: 1,500",
      "  - Retrieved evidence: 5,000",
      "  - Conversation history: 2,500",
      "  - User message + metadata: 200",
      "```",
      "",
      "If you exceed a section budget, compress that section, not the entire prompt randomly.",
      "",
      "## 2.5 Context Window Management",
      "",
      "Every model has a maximum context window. Even before you hit the hard limit, larger contexts have costs:",
      "",
      "- More tokens means more money.",
      "- More tokens can mean more latency.",
      "- More tokens can mean worse instruction-following (too much noise).",
      "",
      "### Truncation is a silent killer",
      "",
      "If your input is truncated:",
      "",
      "- The most recent text often survives.",
      "- The earliest instructions might be chopped.",
      "- You may not notice unless you measure token counts.",
      "",
      "Production rule:",
      "",
      "> Count tokens and enforce budgets before calling the model.",
      "",
      "### Packing strategies for chat history",
      "",
      "1. Recency window: keep only the last N turns.",
      "2. Relevance window: keep turns most related to the current request.",
      "3. Hybrid: keep last few turns plus retrieve older relevant turns.",
      "",
      "### Present evidence in model-friendly formats",
      "",
      "Choose structures that reduce confusion:",
      "",
      "- Policies: bullet points with section ids.",
      "- Database rows: a small table or labeled fields.",
      "- Long docs: extract and label the relevant passages.",
      "",
      "Bad pattern: pasting 30 pages of text with no headings.",
      "",
      "Good pattern:",
      "",
      "```text",
      "Evidence (Refund policy):",
      "- [P1] Refunds allowed within 30 days of purchase.",
      "- [P2] Shipping fees are non-refundable unless Acme is at fault.",
      "",
      "Evidence (Order):",
      "- OrderId: 1234",
      "- Purchase date: 2026-07-01",
      "- Shipping charged: $9.99 (twice)",
      "```",
      "",
      "## 2.6 Context Compression",
      "",
      "Compression is not only summarization. It is: fit the important information into fewer tokens without losing the meaning you need.",
      "",
      "### Common compression techniques",
      "",
      "1. Extractive compression: keep only relevant quotes/snippets.",
      "2. Abstractive compression: summarize into a shorter representation.",
      "3. Structured compression: convert prose to a table, list, or JSON.",
      "4. Hierarchical compression: summary -> outline -> details on demand.",
      "",
      "### When summarization helps (and when it hurts)",
      "",
      "Summaries help when you need long history but only the gist matters.",
      "Summaries hurt when exact wording matters (policy, legal text) or when debugging requires details.",
      "",
      "Production trick:",
      "",
      "> Keep both: a short summary plus pointers to original sources (ids, links, document offsets).",
      "",
      "## 2.7 Conversation Memory",
      "",
      "Memory is information that persists across requests.",
      "",
      "Two kinds:",
      "",
      "1. Short-term memory: recent conversation turns.",
      "2. Long-term memory: stable facts/preferences about the user.",
      "",
      "### What should be stored as memory",
      "",
      "Good candidates:",
      "",
      "- 'Prefer concise answers'",
      "- 'Uses British spelling'",
      "- 'Project is a Next.js app'",
      "",
      "Bad candidates:",
      "",
      "- Secrets (API keys, passwords)",
      "- Temporary tasks unless truly persistent",
      "- Unverified inferences ('User is definitely a senior engineer')",
      "",
      "### Memory failure modes",
      "",
      "- Stale memory: user changed preference but memory persists.",
      "- Contaminated memory: memory stores a hallucination as fact.",
      "- Overconfident memory: memory overrides the user's current request.",
      "",
      "Mitigations:",
      "",
      "- Treat memory as suggestions, not hard truth.",
      "- Store source and timestamp for memory items.",
      "- Prefer user-confirmed facts over inferred facts.",
      "",
      "## 2.8 Long-Context Strategies",
      "",
      "Long context is tempting: 'Just stuff everything in and let the model figure it out.' In practice, long context requires strategy.",
      "",
      "### Strategy A: retrieval over raw history",
      "",
      "Instead of pasting all history, retrieve relevant pieces (vector search over prior turns, keyword search for entities).",
      "",
      "### Strategy B: map-reduce style prompting",
      "",
      "For very long documents:",
      "",
      "1. Chunk the document.",
      "2. Summarize each chunk into structured notes.",
      "3. Combine notes into a final answer.",
      "",
      "This is slower (multiple calls) but can be more reliable than one giant context.",
      "",
      "### Strategy C: answer, then cite",
      "",
      "For grounded answers:",
      "",
      "1. Produce an answer using only the provided evidence.",
      "2. Attach citations to evidence ids.",
      "3. Validate that citations correspond to retrieved passages.",
      "",
      "## 2.9 Prompt Templates",
      "",
      "Templates are how you keep prompts maintainable. Treat templates like code:",
      "",
      "- Inputs are variables (user message, policy snippets, evidence list).",
      "- Output is a structured message list.",
      "",
      "### Template design rules",
      "",
      "1. Keep instructions stable; put volatile content in variables.",
      "2. Avoid complex logic in strings; keep logic in code.",
      "3. Prefer labeled sections with consistent names.",
      "",
      "Example template skeleton:",
      "",
      "```text",
      "System: (role + hard rules)",
      "",
      "Developer:",
      "Task:",
      "- ...",
      "",
      "Constraints:",
      "- Output must be valid JSON matching this schema: ...",
      "",
      "Evidence:",
      "{evidence_blocks}",
      "",
      "User:",
      "{user_message}",
      "```",
      "",
      "## 2.10 Prompt Versioning",
      "",
      "If you do not version prompts, you cannot reproduce old behavior, roll back regressions, or understand which change improved quality.",
      "",
      "### A minimal versioning approach",
      "",
      "- Every prompt/template has an id (for example: `support_reply_v7`).",
      "- The id is logged with each request.",
      "- You can deploy a new version behind a feature flag.",
      "",
      "### How to roll out changes safely",
      "",
      "1. Run offline evals on your golden set.",
      "2. Shadow the new version in production (do not show to users; compare outputs).",
      "3. Gradually ramp traffic to the new version.",
      "4. Monitor costs, latency, and user feedback.",
      "",
      "## Common Mistakes",
      "",
      "### Mistake: mixing evidence and instructions",
      "",
      "If evidence is mixed into instructions, the model can confuse policy with example.",
      "",
      "Fix: separate 'Rules' from 'Evidence', label evidence with ids, and keep it factual.",
      "",
      "### Mistake: no explicit output contract",
      "",
      "If downstream code expects JSON, specify a schema and validate.",
      "",
      "### Mistake: unbounded memory growth",
      "",
      "Storing everything forever bloats context and increases risk.",
      "",
      "Fix: summarize, expire, and use retrieval for older info.",
      "",
      "## Exercises",
      "",
      "1. Take a real chat transcript (10-20 turns). Design a packing strategy with explicit token budgets for each section.",
      "2. Write a system message for an assistant in a domain you know (finance, education, support). Keep it under 200 tokens. Explain what you omitted and why.",
      "3. Design a memory schema with fields: `fact`, `source`, `timestamp`, `confidence`. Give 5 example memory items and classify whether they are safe to store.",
      "4. Pick a long document (a policy or spec). Outline a map-reduce prompting workflow and estimate its cost and latency compared to a single-call approach.",
      "",
      "## Chapter Summary",
      "",
      "- Context engineering assembles instructions, evidence, state, constraints, and tool interfaces into a reliable input.",
      "- Harness engineering makes context reproducible, observable, and testable.",
      "- System prompts should contain stable, high-priority rules, not entire knowledge bases.",
      "- Token budgeting and careful packing prevent truncation and reduce confusion.",
      "- Memory and compression are powerful but introduce failure modes; design them explicitly.",
      "- Version prompts like code, roll out changes gradually, and measure regressions.",
    ].join("\n"),
  },
  {
    slug: ["foundations", "inference-pipeline"],
    title: "Chapter 3 - The Inference Pipeline",
    description:
      "A student-friendly view of what happens inside an LLM request: tokenization, prefill, decode, streaming, and sampling controls.",
    group: "Part I: Foundations",
    toc: [
      "Why This Matters to Engineers",
      "3.1 Tokenization",
      "3.2 Prompt Encoding",
      "3.3 Prefill Phase",
      "3.4 Decode Phase",
      "3.5 Streaming Tokens",
      "3.6 Sampling",
      "3.7 Token Generation Lifecycle",
      "Common Mistakes",
      "Exercises",
      "Chapter Summary",
    ],
    body: [
      "# Chapter 3 - The Inference Pipeline",
      "",
      "Most production problems in LLM systems eventually touch the inference pipeline:",
      "",
      "- 'Why is this slow?'",
      "- 'Why did it ignore my instruction?'",
      "- 'Why did costs spike?'",
      "- 'Why does it behave differently with small prompt changes?'",
      "",
      "You do not need to be a deep learning researcher to engineer LLM systems, but you do need a correct mental model of what happens during inference.",
      "",
      "This chapter explains the pipeline in plain language, with enough detail to make good production decisions.",
      "",
      "## Why This Matters to Engineers",
      "",
      "If you understand the pipeline, you can:",
      "",
      "- Predict latency changes (prefill vs decode)",
      "- Budget tokens intelligently (input vs output)",
      "- Tune sampling for stability vs creativity",
      "- Decide when to use streaming",
      "- Avoid false assumptions (for example: 'the model reads the whole prompt like a human')",
      "",
      "## 3.1 Tokenization",
      "",
      "Models do not read characters or words. They read tokens.",
      "",
      "Tokenization maps text to token ids:",
      "",
      "```",
      "\"Hello world\" -> [15496, 995]",
      "```",
      "",
      "Exact numbers vary by tokenizer and model, but the idea is stable.",
      "",
      "### Why tokenization matters",
      "",
      "1. Cost: you pay per token (input and output).",
      "2. Limits: models have a maximum context window measured in tokens.",
      "3. Behavior: small formatting changes can change token boundaries and influence output.",
      "",
      "### Common surprises",
      "",
      "- Extra whitespace can matter.",
      "- Long URLs and code can tokenize into many tokens.",
      "- Different languages tokenize differently (some scripts compress well, some do not).",
      "",
      "### Practical habit: treat token counts as first-class metrics",
      "",
      "Measure:",
      "",
      "- Input tokens (context size)",
      "- Output tokens (answer length)",
      "",
      "Then connect them to latency (especially output tokens), cost, and truncation risk.",
      "",
      "## 3.2 Prompt Encoding",
      "",
      "After tokenization, the model converts token ids into vectors (embeddings). You can think of it as:",
      "",
      "```",
      "token_id -> embedding_vector",
      "```",
      "",
      "Then the model processes the sequence with transformer layers.",
      "",
      "### A simplified mental model",
      "",
      "1. Each token starts with an embedding.",
      "2. Each transformer layer updates token representations using attention.",
      "3. The final representation at the last position is used to predict the next token.",
      "",
      "Important engineering implication:",
      "",
      "> The model is not reading top-to-bottom once. It computes representations over the entire provided context to predict the next token.",
      "",
      "## 3.3 Prefill Phase",
      "",
      "The prefill (sometimes called prompt processing) is the work the model does to ingest your input context.",
      "",
      "If your input has N tokens, prefill processes those N tokens to set up internal state for generation.",
      "",
      "### What is produced during prefill?",
      "",
      "The key product is the KV cache used by attention during decoding. You do not need the math to get the engineering point:",
      "",
      "- Prefill cost is proportional to input length.",
      "- Prefill builds reusable state so the model does not reprocess the whole prompt for every generated token.",
      "",
      "### Prefill latency intuition",
      "",
      "If you double the input tokens, prefill time usually increases (often roughly linearly, though hardware and implementation details matter).",
      "",
      "This is why huge contexts increase latency even if you generate a short answer, and why good context packing matters.",
      "",
      "## 3.4 Decode Phase",
      "",
      "The decode phase is where the model generates new tokens, one step at a time:",
      "",
      "```",
      "Given context tokens: x1..xN",
      "Predict next token: x(N+1)",
      "Append it to the sequence",
      "Predict next token: x(N+2)",
      "...",
      "```",
      "",
      "Each step uses the KV cache from prefill plus incremental updates.",
      "",
      "### Decode is why long answers are slow",
      "",
      "Latency often scales with the number of generated tokens.",
      "",
      "Engineering implications:",
      "",
      "- If your product encourages long answers, you will pay in time and cost.",
      "- If you can ask for structured, concise outputs, you reduce decode time.",
      "- Streaming improves UX because users see tokens as they are generated.",
      "",
      "## 3.5 Streaming Tokens",
      "",
      "Streaming means the server sends partial output as soon as it is available.",
      "",
      "Two latencies matter:",
      "",
      "- Time to first token (TTFT): when the user sees the first output.",
      "- Time to last token (TTLT): when the answer is complete.",
      "",
      "Streaming usually improves TTFT perception even when TTLT is unchanged.",
      "",
      "### Engineering considerations for streaming",
      "",
      "1. Cancellation: users stop reading and navigate away. Support aborting generation to save cost.",
      "2. Partial output: the model may revise direction mid-stream. Your UI should tolerate that.",
      "3. Tool calls: if the model calls a tool, you may pause streaming, run the tool, then continue.",
      "",
      "### A useful diagram: where streaming fits",
      "",
      "```",
      "Prefill:  [##########]  (no tokens emitted yet)",
      "Decode:          [#][#][#][#][#][#]  (tokens emitted as generated)",
      "Time:    -------------------------------------------------------->",
      "```",
      "",
      "If TTFT is too slow, look at:",
      "",
      "- Retrieval/tool latency before the model call",
      "- Prefill time (input size)",
      "- Queueing at the model runtime",
      "",
      "## 3.6 Sampling",
      "",
      "At each decode step, the model produces logits (scores) over the vocabulary. Sampling turns logits into an actual next-token choice.",
      "",
      "Think:",
      "",
      "```",
      "logits -> probabilities -> choose token",
      "```",
      "",
      "### Temperature",
      "",
      "- Lower temperature (near 0): more deterministic; picks high-probability tokens.",
      "- Higher temperature: more randomness, more variety, more risk.",
      "",
      "Production guidance:",
      "",
      "- Use low temperature for extraction, classification, JSON, and code edits.",
      "- Use moderate temperature for creative writing and brainstorming.",
      "",
      "### Top-k",
      "",
      "Keep only the k most probable tokens, then sample among them.",
      "",
      "- Pros: avoids extremely low-probability tokens.",
      "- Cons: k is an arbitrary cutoff; behavior can be brittle.",
      "",
      "### Top-p (nucleus sampling)",
      "",
      "Keep the smallest set of tokens whose cumulative probability is at least p, then sample among them.",
      "",
      "- Pros: adapts to the model's confidence.",
      "- Cons: can still allow weird tokens if the distribution is flat.",
      "",
      "### Min-p",
      "",
      "Keep tokens with probability >= min_p * (max probability).",
      "",
      "Intuition:",
      "",
      "- When the model is confident, only a few tokens survive.",
      "- When the model is uncertain, more tokens survive.",
      "",
      "### Beam search (rare in chat products)",
      "",
      "Beam search keeps multiple candidate sequences and picks the best by score.",
      "",
      "Why it is uncommon for chat assistants:",
      "",
      "- Expensive",
      "- Often produces generic, over-optimized responses",
      "- Not a great fit for conversational helpfulness",
      "",
      "Where it can help: short, high-precision generation tasks when you can define a clear scoring function and length control.",
      "",
      "### Stop conditions (often more important than sampling)",
      "",
      "Decoding ends when:",
      "",
      "- The model emits an end-of-sequence token",
      "- You hit max output tokens",
      "- You hit a stop sequence (if configured)",
      "",
      "In production, stop sequences can prevent the model from continuing beyond a JSON object or writing multiple answers.",
      "",
      "## 3.7 Token Generation Lifecycle",
      "",
      "This is the inner loop repeated for every generated token:",
      "",
      "```",
      "1) Compute logits for next token",
      "2) Apply constraints (banned tokens, forced tokens, stop rules)",
      "3) Apply sampling (temperature, top-p/top-k/min-p)",
      "4) Pick next token",
      "5) Append token to output",
      "6) Update KV cache",
      "7) Check stopping criteria",
      "```",
      "",
      "### Why small prompt changes change behavior",
      "",
      "Because tokenization can change, next-token distributions are sensitive, and early differences cascade into different continuations.",
      "",
      "This is normal in probabilistic systems. The engineering response is:",
      "",
      "- Constrain outputs when you need determinism (schemas, low temperature).",
      "- Evaluate changes with a dataset, not with one example.",
      "",
      "## Common Mistakes",
      "",
      "### Mistake: using high temperature for structured outputs",
      "",
      "If you want valid JSON, do not sample like you are writing poetry.",
      "",
      "Fix: lower temperature, specify a schema, and validate outputs.",
      "",
      "### Mistake: ignoring output length",
      "",
      "Long answers feel helpful until you see the bill and the latency.",
      "",
      "Fix: set max output tokens, default to concise answers, and offer an 'expand' UX when users want more detail.",
      "",
      "### Mistake: blaming the model for prefill problems",
      "",
      "If TTFT is slow, the culprit is often too much context (prefill), tool/retrieval latency, or runtime queueing.",
      "",
      "Fix: measure timings by step and reduce input size with better packing.",
      "",
      "## Exercises",
      "",
      "1. Take an example prompt you wrote. Identify token-heavy parts (URLs, code blocks, long docs). Propose a compression plan that reduces input tokens by 30% without removing critical evidence.",
      "2. For three tasks (classification, customer support reply, creative story), propose sampling settings (temperature, top-p/top-k) and justify them.",
      "3. Design a streaming UX for a tool-using assistant. How do you represent 'generating', 'calling a tool', and 'resuming' without confusing the user?",
      "4. Explain TTFT vs TTLT in your own words and list three engineering actions that improve each.",
      "",
      "## Chapter Summary",
      "",
      "- Inference is tokenization -> prefill -> decode; decode generates tokens step-by-step.",
      "- Token counts drive cost, limits, and often latency. Measure them.",
      "- Prefill cost scales with input length; decode cost scales with output length.",
      "- Streaming improves time-to-first-token UX and enables cancellations, but adds orchestration complexity.",
      "- Sampling settings control randomness; use low randomness for structured tasks and higher for creative tasks.",
      "- Reliability comes from constraints, measurement, and evaluation, not from hoping the model behaves.",
    ].join("\n"),
  },
];
