import type { DocPage } from '../pages';

const partVIIIGroup = 'Part VIII - Choosing the Right Technique';
const partIXGroup = 'Part IX - Failure Engineering';

export const part07StrategyFailureCaseStudiesPages: DocPage[] = [
  {
    slug: ['handbook', 'part-viii-choosing-the-right-technique', 'chapter-23-adaptation-strategies'],
    title: 'Chapter 23 - Adaptation Strategies',
    description:
      'A practical decision framework for choosing how to adapt LLM behavior: prompting, in-context learning, RAG, fine-tuning, PEFT, and distillation.',
    group: partVIIIGroup,
    toc: [
      'The Real Question: What Are You Adapting?',
      'A Taxonomy of Adaptation',
      'Prompt Engineering (When It Is Enough)',
      'In-Context Learning (ICL) and Few-Shot Examples',
      'Retrieval-Augmented Generation (RAG)',
      'Fine-Tuning',
      'Parameter-Efficient Fine-Tuning (PEFT)',
      'Distillation',
      'Decision Framework (Step-by-Step)',
      'A Tradeoff Matrix (Pick With Your Eyes Open)',
      'Designing an Experiment Plan',
      'When Each Approach Fails (Failure Signatures)',
      'Production Checklist',
      'Exercises',
      'Summary',
    ],
    body: [
      '# Chapter 23 - Adaptation Strategies',
      '',
      'When someone says, "we need the model to be better," you should immediately ask:',
      '',
      '1. Better at what task, exactly?',
      '2. Better according to which metric (and which users)?',
      '3. Better under which constraints (latency, cost, privacy, reliability)?',
      '',
      'Because "make it better" can mean very different things:',
      '',
      '- Make the answer more accurate on your internal policy docs.',
      '- Make the format consistent (valid JSON, correct fields).',
      '- Make tool calls correct and safe.',
      '- Make the model speak in your brand voice.',
      '- Make the model handle a specialized domain vocabulary.',
      '- Make the model stop hallucinating in certain cases.',
      '',
      'Those problems do not share one best solution. This chapter teaches a practical approach to choosing among:',
      '',
      '- Prompt engineering',
      '- In-context learning (few-shot examples)',
      '- Retrieval-augmented generation (RAG)',
      '- Fine-tuning',
      '- Parameter-efficient fine-tuning (PEFT)',
      '- Distillation',
      '',
      'You will leave with:',
      '',
      '- A decision framework you can apply on real projects',
      '- A tradeoff matrix you can use in design reviews',
      '- A test plan template so you do not "improve" the system by accident',
      '',
      '---',
      '',
      '## The Real Question: What Are You Adapting?',
      '',
      'Adaptation is any method that changes the system behavior for a task. But it helps to label what kind of change you need.',
      '',
      'Use this checklist to classify the problem before you pick a technique:',
      '',
      '1. **Knowledge adaptation**: the model needs access to new or changing facts (company docs, policies, product catalogs).',
      '2. **Format/contract adaptation**: the output must match a strict schema and be machine-consumable.',
      '3. **Style/voice adaptation**: tone, phrasing, or structure should match your product.',
      '4. **Skill adaptation**: the model must learn a procedure (a multi-step workflow) or domain reasoning pattern.',
      '5. **Tool-use adaptation**: the model must call tools correctly (arguments, sequencing, idempotency).',
      '6. **Preference adaptation**: you want a particular answer shape even when multiple are acceptable (ranked preferences).',
      '',
      'A common mistake is treating a knowledge problem as a training problem.',
      '',
      'If you need the latest policy text, training is usually the wrong lever. You want retrieval or a tool call.',
      '',
      '---',
      '',
      '## A Taxonomy of Adaptation',
      '',
      'Think of adaptation techniques as acting at different points in the system:',
      '',
      '```text',
      'User request',
      '  |',
      '  v',
      'Prompt + examples + retrieved context  (prompting / ICL / RAG)',
      '  |',
      '  v',
      'Model parameters (fine-tuning / PEFT / distillation)',
      '  |',
      '  v',
      'Output parsing + validation + repair (schema validation, retries, fallbacks)',
      '  |',
      '  v',
      'User-visible behavior',
      '```',
      '',
      'The further down you go, the slower the iteration and the higher the operational cost, but the more you can shape behavior in a stable way.',
      '',
      '---',
      '',
      '## Prompt Engineering (When It Is Enough)',
      '',
      'Prompt engineering is the default first move because it is cheap, fast, and reversible.',
      '',
      'Prompting works best for:',
      '',
      '- Clarifying the task and constraints',
      '- Establishing roles and tone',
      '- Providing output formats and explicit rubrics',
      '- Adding "do not do X" safety constraints (with external enforcement where needed)',
      '',
      'Prompting works poorly for:',
      '',
      '- Adding new factual knowledge that changes frequently',
      '- Guaranteeing strict output contracts without validators',
      '- Making brittle behaviors robust across long-tail inputs',
      '',
      '### A Prompting Pattern That Scales: Contracts + Validators',
      '',
      'Treat prompts like API contracts. Write them like you would write a spec:',
      '',
      '1. Inputs: what the model will see (and what it will not see)',
      '2. Objective: what success looks like',
      '3. Constraints: safety, formatting, "never do" rules',
      '4. Output contract: schema or structured format',
      '5. Failure behavior: what to do when it cannot comply (ask a question, refuse, return an error object)',
      '',
      'Example (structure, not magic words):',
      '',
      '```text',
      'Task: Extract a calendar event from a user message.',
      'Constraints:',
      '- Output MUST be a single JSON object matching the schema below.',
      '- If required fields are missing, ask exactly one clarifying question.',
      '- Never invent attendees, times, or locations.',
      '```',
      '',
      'Then enforce it with:',
      '',
      '- JSON/schema validation',
      '- Retry with a repair prompt (bounded)',
      '- Fallback behavior (human handoff, simplified response)',
      '',
      'Prompting is not a replacement for validation; it is a way to reduce the validator error rate.',
      '',
      '---',
      '',
      '## In-Context Learning (ICL) and Few-Shot Examples',
      '',
      'In-context learning (ICL) means giving the model examples inside the prompt. The examples act like training data, but only for that request.',
      '',
      'ICL is useful when:',
      '',
      '- The desired behavior is hard to describe but easy to show',
      '- You have a small set of canonical examples',
      '- You want fast iteration without training',
      '',
      'ICL tends to fail when:',
      '',
      '- The examples are too long (context cost grows quickly)',
      '- The model overfits to the examples and misses novel cases',
      '- You have many classes/labels and need broad coverage',
      '',
      '### Few-Shot Example Design Rules',
      '',
      '1. **Diversity beats quantity**: 3 diverse examples often outperform 10 similar examples.',
      '2. **Match the real distribution**: include the messy cases (typos, partial info, ambiguous phrasing).',
      '3. **Include negative examples**: show what refusal/clarification looks like.',
      '4. **Keep the output short and consistent**: do not let examples teach accidental formatting.',
      '',
      '### An ICL Template (You Can Reuse)',
      '',
      '```text',
      'You will be given an input. Produce an output in the same style as the examples.',
      '',
      'Example 1',
      'Input: ...',
      'Output: ...',
      '',
      'Example 2',
      'Input: ...',
      'Output: ...',
      '',
      'Now do the task.',
      'Input: {USER_INPUT}',
      'Output:',
      '```',
      '',
      'ICL is especially strong for formatting, classification labels, and consistent writing style.',
      '',
      '---',
      '',
      '## Retrieval-Augmented Generation (RAG)',
      '',
      'RAG is the default answer to the question: "How do we make the system answer using our documents?"',
      '',
      'RAG is not just search. RAG is an end-to-end pipeline:',
      '',
      '```text',
      'User question -> retrieval -> ranking -> context packing -> generation -> citations/grounding checks',
      '```',
      '',
      'RAG is usually the best choice when:',
      '',
      '- Knowledge changes often (policies, product docs, pricing)',
      '- You need citations or traceability',
      '- Data must stay private and cannot be used for training',
      '- You cannot wait for a training pipeline',
      '',
      'RAG is usually not enough when:',
      '',
      '- The model must learn a new skill, not just read facts',
      '- You need sub-second latency and retrieval is too slow (without caching)',
      '- The task depends heavily on formatting or tool correctness (you still need validators)',
      '',
      '### Architecture Pattern: RAG + Tool Verification',
      '',
      'A strong production pattern is:',
      '',
      '1. Retrieve policies/docs',
      '2. Generate answer with citations',
      '3. Run a lightweight checker (rules or a second model) to verify that every key claim is supported by a cited chunk',
      '4. If verification fails, ask for clarification or refuse rather than hallucinating',
      '',
      'This is a systems approach: retrieval reduces hallucination, and verification reduces citation laundering.',
      '',
      '---',
      '',
      '## Fine-Tuning',
      '',
      'Fine-tuning updates model weights using your training data.',
      '',
      'Fine-tuning is appropriate when you need the model to learn:',
      '',
      '- A consistent style/voice across many outputs',
      '- A domain-specific response pattern that prompting cannot reliably enforce',
      '- A classification/extraction behavior with stable label definitions',
      '- Tool-use reliability improvements via supervised traces (with care)',
      '',
      'Fine-tuning is a risky choice for "just add knowledge." If your knowledge changes weekly, fine-tuning can become a treadmill.',
      '',
      '### Fine-Tuning Data: What It Really Is',
      '',
      'Training data is not a pile of examples. It is a specification encoded as examples.',
      '',
      'Bad training data does not just "not help." It can teach the model the wrong behavior in a sticky way.',
      '',
      'A good fine-tuning dataset has:',
      '',
      '- Clear task definition and labeling rules',
      '- Coverage of the real distribution (including edge cases)',
      '- Negative cases (refusals, safe completions, "ask a clarifying question")',
      '- Separation between training, validation, and regression tests',
      '',
      '### Deployment Reality',
      '',
      'Fine-tuning adds operational obligations:',
      '',
      '- Dataset versioning',
      '- Repeatable training jobs',
      '- Evaluation gates before deployment',
      '- Model versioning and rollback',
      '',
      'If you cannot commit to those, do not fine-tune yet.',
      '',
      '---',
      '',
      '## Parameter-Efficient Fine-Tuning (PEFT)',
      '',
      'PEFT methods (for example, adapter-style approaches) aim to get many of the benefits of fine-tuning with fewer trainable parameters.',
      '',
      'You should think of PEFT as:',
      '',
      '- Faster to train',
      '- Often cheaper to store and iterate',
      '- Sometimes easier to maintain multiple variants (per tenant, per domain)',
      '',
      'PEFT is helpful when:',
      '',
      '- You need to adapt behavior but want shorter training cycles',
      '- You want multiple specialized variants without maintaining many full model copies',
      '',
      'PEFT does not remove the need for:',
      '',
      '- Great training data',
      '- Evaluation',
      '- Versioning, rollback, and monitoring',
      '',
      '---',
      '',
      '## Distillation',
      '',
      'Distillation trains a smaller "student" model to imitate a stronger "teacher" model (or an expensive system pipeline).',
      '',
      'Distillation is appropriate when:',
      '',
      '- You have a working system that is too expensive or slow',
      '- You want to move capability to a smaller model for latency/cost reasons',
      '- You need consistent behavior under tight constraints (for example, on-device or high-throughput serving)',
      '',
      'Distillation often looks like this:',
      '',
      '```text',
      'Teacher system (expensive) -> generate supervised traces -> train student -> validate -> deploy student',
      '```',
      '',
      'Important: you are distilling behavior, not truth. If your teacher system has systematic errors, the student will learn them efficiently.',
      '',
      '---',
      '',
      '## Decision Framework (Step-by-Step)',
      '',
      'Use this framework in a design review. The point is not to be "right." The point is to force clarity.',
      '',
      '### Step 1: Write the acceptance tests first',
      '',
      'Pick 30 to 200 examples of real tasks and define success. Include:',
      '',
      '- Correctness (with sources if needed)',
      '- Contract adherence (schema, tool calls, safety rules)',
      '- Latency and cost budgets',
      '',
      'If you cannot state what "better" means, you cannot choose an adaptation strategy.',
      '',
      '### Step 2: Classify the failure',
      '',
      'For each failing example, label the dominant failure type:',
      '',
      '- Knowledge missing / outdated',
      '- Reasoning / skill gap',
      '- Format / parsing failure',
      '- Tool-use error',
      '- Safety/policy failure',
      '- Product UX failure (user did not provide required info)',
      '',
      '### Step 3: Ask the data questions',
      '',
      '1. Do you have the right data to teach the behavior?',
      '2. Can you collect it safely and legally?',
      '3. Does it change frequently?',
      '4. Is it private (and cannot leave your boundary)?',
      '',
      '### Step 4: Choose the lowest-cost lever that can plausibly work',
      '',
      'Use this ordering as a default:',
      '',
      '1. Prompting + validators + guardrails',
      '2. Add ICL examples for consistent patterns',
      '3. Add RAG/tooling for private or changing knowledge',
      '4. Fine-tune/PEFT for stable behavior changes and skills',
      '5. Distill when you already have an expensive working pipeline that you need to compress',
      '',
      '### Step 5: Define your rollback and monitoring plan',
      '',
      'Every adaptation method can regress something. Plan how you will detect regressions and how you will undo the change quickly.',
      '',
      '---',
      '',
      '## A Tradeoff Matrix (Pick With Your Eyes Open)',
      '',
      'The table below is not "the truth." It is a useful forcing function. Score each axis for your specific product.',
      '',
      'Axes:',
      '',
      '- Iteration speed',
      '- Upfront engineering cost',
      '- Runtime cost (tokens, tool calls, compute)',
      '- Latency impact',
      '- Reliability/consistency',
      '- Knowledge freshness',
      '- Traceability/citations',
      '- Operational burden',
      '',
      '```text',
      'Technique   | Iteration | Upfront Eng | Runtime Cost | Latency | Consistency | Freshness | Traceability | Ops Burden',
      '----------- | --------- | ----------- | ------------ | ------- | ----------- | --------- | ------------ | ----------',
      'Prompting   | Fast      | Low         | Low-Med      | Low     | Med         | Low       | Low          | Low',
      'ICL         | Fast      | Low         | Med          | Med     | Med         | Low       | Low          | Low',
      'RAG         | Med       | Med-High    | Med          | Med     | Med-High    | High      | High         | Med-High',
      'Fine-tune   | Slow      | High        | Low          | Low     | High        | Low       | Low          | High',
      'PEFT        | Med       | Med         | Low          | Low     | High        | Low       | Low          | Med',
      'Distill     | Slow      | High        | Very Low     | Very Low| Med-High    | Low       | Low          | High',
      '```',
      '',
      'How to read it:',
      '',
      '- RAG wins on freshness and traceability but adds moving parts.',
      '- Fine-tuning/PEFT win on consistency and runtime cost but increase ML ops obligations.',
      '- Distillation wins on cost and latency, but requires a working teacher and a solid evaluation harness.',
      '',
      '---',
      '',
      '## Designing an Experiment Plan',
      '',
      'Students often run experiments backwards: they build the fancy thing first, then try to prove it helped.',
      '',
      'A better plan:',
      '',
      '1. Define metrics and an evaluation set (offline).',
      '2. Build the smallest viable change.',
      '3. Compare against baseline and look at slices (not just average).',
      '4. Only then consider increasing complexity.',
      '',
      '### A Minimal Experiment Report Template',
      '',
      '```text',
      'Change: (what changed)',
      'Hypothesis: (why it should help)',
      'Evaluation set: size, source, slices',
      'Primary metrics: (and thresholds)',
      'Secondary metrics: safety, latency, cost',
      'Results: overall + slices',
      'Failure analysis: top 5 new failures',
      'Decision: ship / iterate / revert',
      '```',
      '',
      '---',
      '',
      '## When Each Approach Fails (Failure Signatures)',
      '',
      'You can often tell what to do next by recognizing failure signatures.',
      '',
      '### Prompting Failure Signatures',
      '',
      '- Output is inconsistent across paraphrases.',
      '- The model follows the prompt on easy cases but breaks on edge cases.',
      '- The model "sounds confident" but violates strict contracts occasionally.',
      '',
      'Next step: add validators, add few-shot examples, or move to a method that changes the underlying behavior.',
      '',
      '### ICL Failure Signatures',
      '',
      '- Behavior is strongly dependent on which examples are included.',
      '- Long prompts cause latency/cost spikes.',
      '- The model copies example content or overfits to superficial patterns.',
      '',
      'Next step: reduce examples, improve example diversity, or move stable patterns into fine-tuning.',
      '',
      '### RAG Failure Signatures',
      '',
      '- The right document exists, but retrieval does not find it (recall problem).',
      '- Retrieval finds it, but the model ignores it (prompt/packing problem).',
      '- The system cites sources that do not support the claims (grounding/verification problem).',
      '',
      'Next step: instrument retrieval, add reranking, add packing rules, add claim-to-evidence checks.',
      '',
      '### Fine-Tuning/PEFT Failure Signatures',
      '',
      '- Gains on the training distribution but regressions on rare cases.',
      '- Overconfident wrong answers (the model learned "always answer").',
      '- The model becomes less steerable by prompts.',
      '',
      'Next step: improve data, add refusal/uncertainty examples, strengthen eval and rollback.',
      '',
      '### Distillation Failure Signatures',
      '',
      '- Student imitates teacher style but loses hard-case reasoning.',
      '- Student becomes brittle on prompts that were not present in traces.',
      '',
      'Next step: broaden traces, add hard-case curriculum, keep a fallback path to the teacher for difficult inputs.',
      '',
      '---',
      '',
      '## Production Checklist',
      '',
      'Before you ship an adaptation change, verify:',
      '',
      '1. You have an offline evaluation suite with regression gates.',
      '2. You have logs that let you debug failures (inputs, retrieved context, tool calls, validator results).',
      '3. You have a rollback plan (feature flag or versioned prompt/model).',
      '4. You have budget limits (tokens, tool calls, agent steps).',
      '5. You have a safety plan (refusal behavior, policy checks, sandboxing for tools).',
      '6. You have a freshness plan for knowledge (if relevant): update cadence, invalidation, reindexing.',
      '',
      '---',
      '',
      '## Exercises',
      '',
      '1. Pick a feature you care about (support bot, coding assistant, policy Q&A). Write 50 evaluation examples and define success criteria.',
      '2. For 10 failing examples, classify the failure type (knowledge, format, tool use, safety, skill). Propose the lowest-cost lever that could plausibly fix each.',
      '3. Create a tradeoff matrix for your feature and justify your top two candidate strategies.',
      '4. Design a two-week experiment plan with milestones and go/no-go metrics.',
      '',
      '---',
      '',
      '## Summary',
      '',
      '- Adaptation is not one knob; it is a set of techniques that change behavior at different layers of the system.',
      '- Start with acceptance tests and failure classification before choosing a technique.',
      '- Prompting and ICL are fast but can be fragile; validators and guardrails are non-negotiable for strict contracts.',
      '- RAG is the default for private or changing knowledge, but requires retrieval instrumentation and grounding checks.',
      '- Fine-tuning/PEFT are for stable behavior changes and skills, but require ML ops discipline.',
      '- Distillation is for compressing an already-working expensive pipeline into a cheaper/faster model, and it only works as well as your traces and evaluation.',
      '',
    ].join('\n'),
  },
  {
    slug: ['handbook', 'part-viii-choosing-the-right-technique', 'chapter-24-engineering-tradeoffs'],
    title: 'Chapter 24 - Engineering Tradeoffs',
    description:
      'A practical set of frameworks for making AI system tradeoffs: latency, cost, quality, reliability, scalability, and build-vs-buy choices.',
    group: partVIIIGroup,
    toc: [
      'Why Tradeoffs Are Harder in AI Systems',
      'The 6 Core Axes',
      'A Decision Framework: Constraints First',
      'Latency vs Quality',
      'Cost vs Quality',
      'Reliability vs Speed',
      'Scalability vs Complexity',
      'Build vs Buy',
      'Open Source vs API Models',
      'Long Context vs RAG',
      'Tradeoff Matrices You Can Reuse',
      'Production Checklists',
      'Exercises',
      'Summary',
    ],
    body: [
      '# Chapter 24 - Engineering Tradeoffs',
      '',
      'AI systems turn ordinary product decisions into multi-dimensional tradeoffs.',
      '',
      'In a normal web app, you might trade latency against cost by caching more or buying bigger servers.',
      '',
      'In an AI system, a single change can move many levers at once:',
      '',
      '- Changing the model changes quality, cost, and latency.',
      '- Adding retrieval changes quality and factuality, but also adds latency and new failure modes.',
      '- Adding tools can improve correctness, but increases reliability risk and security risk.',
      '- Increasing context length can improve reasoning on some tasks, but can destroy throughput and cost.',
      '',
      'This chapter gives you reusable frameworks for making these decisions without relying on vibes.',
      '',
      '---',
      '',
      '## Why Tradeoffs Are Harder in AI Systems',
      '',
      'There are three reasons:',
      '',
      '1. **Quality is not one thing.** "Better" can mean more accurate, more helpful, more concise, more grounded, more safe, or more compliant with a schema.',
      '2. **Variance is real.** The same prompt can produce different outputs across time, providers, and minor input changes.',
      '3. **The system is a pipeline.** Quality depends on retrieval, tool calls, validators, and UI. Optimizing one component can break another.',
      '',
      'So you need two things:',
      '',
      '- A measurement plan (evaluation + production metrics)',
      '- A decision framework that respects constraints',
      '',
      '---',
      '',
      '## The 6 Core Axes',
      '',
      'Most AI product decisions are combinations of these axes:',
      '',
      '1. **Quality**: task success rate, groundedness, schema pass rate, safety pass rate',
      '2. **Latency**: p50 and p95 end-to-end time, time-to-first-token, tail latency',
      '3. **Cost**: tokens, tool calls, GPU minutes, cache costs, vector DB costs',
      '4. **Reliability**: error rate, timeout rate, degraded-mode frequency, incident rate',
      '5. **Scalability**: ability to handle load growth without exploding engineering effort',
      '6. **Complexity**: operational burden, on-call load, debugging difficulty, number of moving parts',
      '',
      'A strong team makes tradeoffs explicitly across these axes rather than pretending they do not exist.',
      '',
      '---',
      '',
      '## A Decision Framework: Constraints First',
      '',
      'Start tradeoff decisions with constraints, not preferences.',
      '',
      '### Step 1: Write hard constraints',
      '',
      'Examples:',
      '',
      '- p95 latency must be under 2.5 seconds for interactive chat',
      '- answers must cite sources for policy questions',
      '- tool calls must be idempotent and auditable',
      '- system must operate within a per-user daily budget',
      '',
      'Hard constraints are non-negotiable. If a design violates them, it is not a candidate.',
      '',
      '### Step 2: Write soft constraints',
      '',
      'Examples:',
      '',
      '- prefer not to add a new database this quarter',
      '- prefer to keep infra in one cloud',
      '- prefer to avoid training pipelines until the product-market fit is proven',
      '',
      'Soft constraints can be overridden with justification.',
      '',
      '### Step 3: Choose an objective function (for now)',
      '',
      'Pick one primary objective for the decision you are making:',
      '',
      '- maximize task success rate under latency budget',
      '- minimize cost under quality floor',
      '- minimize incident risk under cost ceiling',
      '',
      'You can change the objective later, but you cannot optimize everything at once.',
      '',
      '---',
      '',
      '## Latency vs Quality',
      '',
      'Latency is not just user experience. Latency is also capacity.',
      '',
      'In token-generating systems, latency and throughput are tightly linked. If a request takes longer, it occupies capacity longer, increasing queueing, which increases tail latency, which can cause timeouts, retries, and cascading failures.',
      '',
      '### The Latency Budget Method',
      '',
      'Break the request into components and budget each:',
      '',
      '```text',
      'Total budget (p95): 2500 ms',
      '  - network + auth:      100 ms',
      '  - retrieval:           300 ms',
      '  - prompt building:     100 ms',
      '  - model prefill:       600 ms',
      '  - decoding:           1200 ms',
      '  - post-processing:     200 ms',
      '```',
      '',
      'Then ask: which parts can be reduced without destroying quality?',
      '',
      'Common tactics:',
      '',
      '- Reduce output length with explicit caps',
      '- Stream tokens to reduce perceived latency (time-to-first-token)',
      '- Cache retrieval results for repeated queries',
      '- Use a smaller model for easy cases (routing)',
      '- Use parallel tool calls when safe',
      '',
      '### Quality Improvements That Often Cost Latency',
      '',
      '- Deep retrieval (higher k, hybrid search, reranking)',
      '- Multi-step reasoning (chain-of-thought style prompting, agent loops)',
      '- Verification passes (second model judge, claim checker)',
      '',
      'A practical compromise is a two-tier design:',
      '',
      '- Fast path: best-effort answer under tight budget',
      '- Slow path: high-accuracy answer with verification when the user requests it or when the system detects high risk',
      '',
      '---',
      '',
      '## Cost vs Quality',
      '',
      'You cannot have a serious AI system without cost engineering.',
      '',
      'Most production cost comes from:',
      '',
      '- Tokens (prompt + output)',
      '- Tool calls (including retrieval and external APIs)',
      '- Compute for larger models or long contexts',
      '',
      '### Cost Control Patterns',
      '',
      '1. **Budgets**: per request, per user, per tenant.',
      '2. **Caps**: max output tokens, max retrieved chunks, max tool calls, max agent steps.',
      '3. **Routing**: small model for easy cases; escalate only when validators fail.',
      '4. **Caching**: prompt prefix caching, embedding caching, retrieval caching (with invalidation).',
      '5. **Compression**: shorter prompts via context packing and summarization (with evaluation).',
      '',
      '### A Cost/Quality Tradeoff Matrix (Example)',
      '',
      'Score each option from 1 (bad) to 5 (good) for your system:',
      '',
      '```text',
      'Option                         | Quality | Cost | Notes',
      '------------------------------ | ------- | ---- | -----',
      'Bigger model always            | 5       | 1    | Simple, expensive, hard to scale',
      'Smaller model + RAG            | 4       | 3    | Great for knowledge, not always for reasoning',
      'Router: small then escalate    | 4       | 4    | Needs validators and good logging',
      'Add verification pass always   | 5       | 2    | Strong correctness, slower and costly',
      '```',
      '',
      'The goal is not to compute "the answer." The goal is to force a discussion of which costs you are actually paying.',
      '',
      '---',
      '',
      '## Reliability vs Speed',
      '',
      'Reliability improvements often add latency:',
      '',
      '- Retries improve success rate but can double latency and cost.',
      '- Timeouts protect the system but can reduce success for slow dependencies.',
      '- Verification improves correctness but adds extra model calls.',
      '',
      '### A Useful Rule: Bounded Work',
      '',
      'Most reliability issues in AI systems come from unbounded work:',
      '',
      '- unbounded output length',
      '- unbounded agent loops',
      '- unbounded retries',
      '- unbounded tool call chains',
      '',
      'If you bound the work, you can reason about performance and failure behavior.',
      '',
      '### Reliability Ladder (Degrade Gracefully)',
      '',
      'Design reliability as a ladder, not a binary:',
      '',
      '1. Full capability (RAG + tools + verification)',
      '2. Reduced capability (RAG only, no tools)',
      '3. Minimal capability (template guidance, ask clarifying questions)',
      '4. Safe failure (refuse with clear next steps)',
      '',
      'The tradeoff is explicit: you preserve availability by reducing capability under stress.',
      '',
      '---',
      '',
      '## Scalability vs Complexity',
      '',
      'A system that "works" for 10 requests per minute may collapse at 1,000 requests per minute.',
      '',
      'Scaling AI systems is not just adding servers. It is managing shared bottlenecks:',
      '',
      '- model provider limits (requests/tokens per minute)',
      '- GPU memory and KV cache pressure (if self-hosted)',
      '- vector DB latency under concurrent load',
      '- tool API rate limits',
      '',
      '### Complexity Tax',
      '',
      'Every new component adds failure modes:',
      '',
      '- retriever outage',
      '- index staleness',
      '- tool schema drift',
      '- cache invalidation bugs',
      '',
      'So you should add components only when they pay rent in your metrics.',
      '',
      '---',
      '',
      '## Build vs Buy',
      '',
      'Build vs buy is a decision about control, cost, and risk.',
      '',
      '### Buy (Managed APIs) tends to win when:',
      '',
      '- you need to ship quickly',
      '- your team is small',
      '- your scale is modest or unpredictable',
      '- you value reliability and time-to-market over customization',
      '',
      '### Build (Self-host / deep customization) tends to win when:',
      '',
      '- you need strict data residency or offline operation',
      '- your unit economics demand lower marginal cost',
      '- you need deep control over latency or model behavior',
      '- you can staff ML ops and reliability work',
      '',
      '### A Decision Checklist',
      '',
      'Answer honestly:',
      '',
      '1. Can you operate GPUs and model serving with an on-call rotation?',
      '2. Do you have a clear plan to monitor quality regressions and roll back?',
      '3. Are your costs dominated by model inference, or by engineering time?',
      '4. Do you need features that managed services do not provide (custom kernels, custom safety filters, special routing)?',
      '',
      '---',
      '',
      '## Open Source vs API Models',
      '',
      'This tradeoff is similar to build vs buy, but with extra dimensions:',
      '',
      '- licensing and redistribution constraints',
      '- model updates and compatibility',
      '- security posture and supply chain',
      '- fine-tuning and customization freedom',
      '',
      'A useful framing:',
      '',
      '- Open models often give you control and customization, but you own the reliability and performance work.',
      '- API models often give you reliability and fast iteration, but you accept provider constraints and pricing.',
      '',
      'Many production stacks are hybrid: open models for high-volume or specialized tasks, API models for high-stakes or hard tasks.',
      '',
      '---',
      '',
      '## Long Context vs RAG',
      '',
      'Teams often ask: should we just increase context and paste more text?',
      '',
      'Long context can be powerful, but it is not a free replacement for retrieval.',
      '',
      '### Long Context tends to win when:',
      '',
      '- the relevant information is already in the conversation',
      '- you need cross-document reasoning where retrieval is hard to do well',
      '- the set of documents is small and stable',
      '',
      '### RAG tends to win when:',
      '',
      '- you have many documents and need relevance filtering',
      '- you need freshness and updates',
      '- you need permission filtering and auditable citations',
      '',
      '### Hybrid Pattern',
      '',
      'A common production pattern is:',
      '',
      '- keep conversation context concise via summaries',
      '- retrieve only the top relevant chunks',
      '- pack context with strict budgets (max tokens per source)',
      '',
      'This gives you the benefits of both without paying the worst costs of either.',
      '',
      '---',
      '',
      '## Tradeoff Matrices You Can Reuse',
      '',
      '### Matrix 1: Response Strategy',
      '',
      '```text',
      'Strategy                   | Latency | Cost | Quality | Reliability | Notes',
      '-------------------------- | ------- | ---- | ------- | ----------- | -----',
      'Single model, no tools     | Low     | Med  | Med     | High        | Simple, but limited knowledge',
      'RAG only                   | Med     | Med  | High*   | Med         | High when answer is in docs; needs retrieval quality',
      'Tools + RAG + verification | High    | High | Very High| Med-High   | Best correctness, highest complexity',
      'Agent loop                 | High    | High | Variable | Low-Med     | Needs strict step budgets and instrumentation',
      '```',
      '',
      'The "*" is a reminder: RAG quality depends on retrieval recall.',
      '',
      '### Matrix 2: Rollout Strategy',
      '',
      '```text',
      'Rollout         | Risk | Speed | When to use',
      '--------------- | ---- | ----- | -----------',
      'Big bang        | High | Fast  | Never for critical systems',
      'Gradual %       | Med  | Med   | Default for model/prompt changes',
      'Shadow          | Low  | Slow  | Great for high-stakes workflows; compare outputs offline',
      'A/B test        | Med  | Med   | When you have a measurable user outcome',
      '```',
      '',
      '---',
      '',
      '## Production Checklists',
      '',
      '### Tradeoff Review Checklist',
      '',
      '1. What is the primary metric we are optimizing?',
      '2. What are the hard constraints (latency, cost, safety, privacy)?',
      '3. What is the fallback/degraded mode?',
      '4. What is the rollback mechanism (prompt version, model version, feature flag)?',
      '5. What is the evaluation suite that prevents regressions?',
      '6. What new failure modes does this design introduce?',
      '',
      '### Performance Checklist',
      '',
      '1. Measure p50 and p95 end-to-end latency.',
      '2. Measure time-to-first-token separately from total generation time.',
      '3. Track output length distribution (it drives cost and latency).',
      '4. Track tool-call latency and error rates (each dependency can dominate tail latency).',
      '',
      '---',
      '',
      '## Exercises',
      '',
      '1. Choose an AI feature and define hard constraints (latency/cost/safety). Then propose two architectures and score them on the 6 axes.',
      '2. Build a latency budget table for a RAG+tool system. Identify the biggest tail-latency contributors and propose two mitigations.',
      '3. Design a degradation ladder for a provider outage. What is the user-visible behavior at each rung?',
      '4. Write a build-vs-buy memo in one page: assumptions, risks, and the minimum staffing required to operate the "build" option safely.',
      '',
      '---',
      '',
      '## Summary',
      '',
      '- AI system decisions are multi-dimensional; write constraints and objectives before debating solutions.',
      '- Latency is capacity, and unbounded work is the enemy of reliability.',
      '- Cost control requires budgets, caps, routing, caching, and measurement.',
      '- Reliability is a ladder (degrade gracefully), not a binary.',
      '- Scaling adds complexity; add components only when they pay rent in metrics.',
      '- Build vs buy and open vs API are decisions about control, staffing, risk, and unit economics.',
      '',
    ].join('\n'),
  },
  {
    slug: ['handbook', 'part-ix-failure-engineering', 'chapter-25-production-failure-modes'],
    title: 'Chapter 25 - Production Failure Modes',
    description:
      'A failure-mode catalog for AI systems with postmortem-style examples, detection signals, mitigations, and production checklists.',
    group: partIXGroup,
    toc: [
      'How To Use This Chapter',
      'The Failure-Mode Mindset',
      '25.1 Hallucinated Tool Calls',
      '25.2 Malformed JSON',
      '25.3 Infinite Agent Loops',
      '25.4 Context Overflow',
      '25.5 Stale Retrieval',
      '25.6 Cache Thrashing',
      '25.7 Silent Evaluation Regressions',
      '25.8 Prompt Drift',
      '25.9 Race Conditions',
      '25.10 Cascading Failures',
      'Production Readiness Checklist (AI-Specific)',
      'Incident Response: What To Capture',
      'Exercises',
      'Summary',
    ],
    body: [
      '# Chapter 25 - Production Failure Modes',
      '',
      'Traditional software fails in familiar ways: null pointers, timeouts, bad deploys.',
      '',
      'AI systems fail in those ways too, but they add a new category:',
      '',
      '- **semantic failures**: the system returns something that looks plausible but is wrong, unsafe, or violates contracts.',
      '',
      'This chapter is a catalog of common AI production failure modes with:',
      '',
      '- Symptoms (what you see in logs and user reports)',
      '- Root causes (what is actually happening)',
      '- Detection signals (what to monitor)',
      '- Mitigations (design patterns and operational controls)',
      '- Postmortem-style examples (how incidents unfold)',
      '',
      '---',
      '',
      '## How To Use This Chapter',
      '',
      'Read it once to learn the landscape. Then use it as a reference:',
      '',
      '- During design reviews: "Which of these failure modes are we exposed to?"',
      '- During incidents: "Which failure signature matches what we are seeing?"',
      '- During postmortems: "Which mitigations were missing?"',
      '',
      '---',
      '',
      '## The Failure-Mode Mindset',
      '',
      'In production, you should assume:',
      '',
      '- The model will occasionally produce an invalid output.',
      '- Dependencies will be slow or down.',
      '- Retrieval will sometimes miss the right document.',
      '- Users will provide incomplete or adversarial inputs.',
      '- Updates (model, prompt, index, tools) will regress something.',
      '',
      'So the goal is not "never fail." The goal is:',
      '',
      '- fail safely',
      '- detect quickly',
      '- recover gracefully',
      '- learn systematically',
      '',
      '---',
      '',
      '## 25.1 Hallucinated Tool Calls',
      '',
      '### What it looks like',
      '',
      '- The model calls a tool that does not exist.',
      '- The model calls a real tool with the wrong arguments.',
      '- The model "pretends" it called a tool and fabricates results.',
      '',
      '### Why it happens',
      '',
      '- The model is trying to be helpful and fills in missing details.',
      '- Tool schemas drift and the prompt/tool list is outdated.',
      '- The model is not given enough context to decide whether a tool is allowed or necessary.',
      '',
      '### Detection signals',
      '',
      '- Tool-call validation failures (schema mismatch rate)',
      '- Tool-call retries increasing',
      '- Spike in downstream 4xx errors due to bad arguments',
      '- User reports of actions they did not request (high severity)',
      '',
      '### Mitigations',
      '',
      '1. **Strict tool allow-list**: the model can only call tools you expose in the runtime.',
      '2. **Schema validation**: reject tool calls that do not validate. Log the exact failure.',
      '3. **Idempotency keys** for side-effecting actions.',
      '4. **Confirmation gates** for dangerous actions (delete, send money, email external recipients).',
      '5. **Tool results are source of truth**: never accept "claimed tool output" from the model.',
      '',
      '### Postmortem-style example',
      '',
      '```text',
      'Incident: unintended email sent to customer',
      'Impact: 37 customers received an incorrect billing notice',
      '',
      'Timeline:',
      '- 10:02: new prompt deployed to improve "helpfulness"',
      '- 10:15: tool-call validation errors increased but alert threshold not met',
      '- 10:41: model begins calling send_email with inferred recipients',
      '- 11:05: support reports customers receiving emails',
      '- 11:08: feature flag disabled; incident stops',
      '',
      'Root cause:',
      '- prompt encouraged proactive action without confirmation',
      '- send_email tool did not require an explicit confirmation token from UI',
      '- no idempotency, so retries duplicated sends',
      '',
      'Fixes:',
      '- require UI confirmation for send_email',
      '- add idempotency keys',
      '- add alert on "dangerous tool used without explicit user confirmation"',
      '```',
      '',
      '---',
      '',
      '## 25.2 Malformed JSON',
      '',
      '### What it looks like',
      '',
      '- Parser errors (JSON.parse failures)',
      '- Schema validation failures (wrong types, missing fields)',
      '- Streaming truncation mid-object',
      '',
      '### Why it happens',
      '',
      '- The model outputs extra text around JSON.',
      '- The model forgets schema constraints on long responses.',
      '- The output is cut off due to token limits or timeouts.',
      '',
      '### Detection signals',
      '',
      '- JSON parse failure rate',
      '- Schema validation failure rate by field',
      '- Truncation indicators (output ends abruptly, unterminated braces)',
      '',
      '### Mitigations',
      '',
      '1. Use constrained decoding / strict JSON mode when available.',
      '2. Validate and repair with bounded retries (do not loop forever).',
      '3. Keep schemas small; use enums and discriminated unions.',
      '4. Separate "explanation" text from "machine output" channels (two fields, or two calls).',
      '',
      '### Postmortem-style example',
      '',
      '```text',
      'Incident: checkout workflow broke for 6% of users',
      'Impact: conversion drop for 42 minutes',
      '',
      'Root cause:',
      '- new model version produced trailing commas more frequently',
      '- app assumed JSON was always valid; no repair path',
      '',
      'Fixes:',
      '- add schema validation + one repair attempt',
      '- add fallback to a simpler extraction prompt when validation fails',
      '- add monitoring on "schema pass rate" not just HTTP 500 rate',
      '```',
      '',
      '---',
      '',
      '## 25.3 Infinite Agent Loops',
      '',
      '### What it looks like',
      '',
      '- Requests run for a long time and time out.',
      '- Repeated tool calls with small variations.',
      '- Cost spikes (tokens and tool calls) on a subset of requests.',
      '',
      '### Why it happens',
      '',
      '- No termination condition beyond "keep trying".',
      '- The agent cannot tell that it is stuck (missing state, missing progress signals).',
      '- Tools return errors that the agent misinterprets as "try again".',
      '',
      '### Detection signals',
      '',
      '- Step count distribution (p95 step count increases)',
      '- Tool call repeats per request',
      '- Cost per request outliers (long tail)',
      '',
      '### Mitigations',
      '',
      '1. **Hard budgets**: max steps, max tool calls, max tokens, max wall-clock time.',
      '2. **Progress checks**: require each step to add new information; stop if repeating.',
      '3. **Tool error classification**: do not retry non-retryable errors.',
      '4. **Escape hatch**: ask the user a clarifying question or return a partial result.',
      '',
      '### Postmortem-style example',
      '',
      '```text',
      'Incident: cost spike and degraded latency',
      'Impact: p95 latency doubled; token spend tripled for 2 hours',
      '',
      'Root cause:',
      '- agent kept re-running a "search" tool because results were empty',
      '- no cap on tool calls; no "no results" terminal state',
      '',
      'Fixes:',
      '- max 3 search attempts per request',
      '- if no results, ask the user for more specifics',
      '- alert on "tool_calls_per_request" anomaly',
      '```',
      '',
      '---',
      '',
      '## 25.4 Context Overflow',
      '',
      '### What it looks like',
      '',
      '- Provider rejects requests due to context length.',
      '- The model ignores important earlier instructions.',
      '- Truncation removes critical tool results or policy text.',
      '',
      '### Why it happens',
      '',
      '- Conversations grow without summarization.',
      '- Retrieval adds too many chunks.',
      '- Tools return large blobs (HTML, logs) that are shoved into the prompt.',
      '',
      '### Detection signals',
      '',
      '- Prompt token count distribution (p95 climbing over time)',
      '- Percentage of requests hitting truncation/cap',
      '- Increased instruction-following failures on long conversations',
      '',
      '### Mitigations',
      '',
      '1. **Context budgets by component**: conversation history, retrieval, tool outputs each get a max token allowance.',
      '2. **Summarize with intent**: keep decisions and user constraints, drop chatter.',
      '3. **Tool output shaping**: tools should return structured, minimal fields, not raw dumps.',
      '4. **Retrieval packing**: cap chunks per source; prefer shorter relevant passages.',
      '',
      '---',
      '',
      '## 25.5 Stale Retrieval',
      '',
      '### What it looks like',
      '',
      '- The system confidently answers using outdated policy/docs.',
      '- Citations point to documents that were superseded.',
      '',
      '### Why it happens',
      '',
      '- Indexing pipeline lags behind source changes.',
      '- Cache invalidation fails (retrieval cached too long).',
      '- The system does not encode freshness as a ranking feature.',
      '',
      '### Detection signals',
      '',
      '- Time since last index update',
      '- Retrieval results skewing toward old timestamps',
      '- User reports: "policy changed last week"',
      '',
      '### Mitigations',
      '',
      '1. Track doc versions and timestamps; include in retrieval metadata.',
      '2. Add freshness-aware ranking or filtering for certain doc classes (policies, pricing).',
      '3. Cache with explicit invalidation keys (doc version, index version), not only TTL.',
      '4. For high-stakes answers, verify with a source-of-truth API rather than relying only on docs.',
      '',
      '---',
      '',
      '## 25.6 Cache Thrashing',
      '',
      '### What it looks like',
      '',
      '- Latency spikes under load.',
      '- GPU memory pressure or OOMs (self-hosted) due to KV cache pressure.',
      '- Low cache hit rates despite high traffic.',
      '',
      '### Why it happens',
      '',
      '- Working set does not fit in cache.',
      '- Cache keys are too specific (low reuse).',
      '- Eviction policy is misaligned with traffic (e.g., LRU with bursty long requests).',
      '',
      '### Detection signals',
      '',
      '- Cache hit rate over time',
      '- Evictions per second',
      '- Correlation between cache evictions and latency spikes',
      '',
      '### Mitigations',
      '',
      '1. Measure working set size; do not guess.',
      '2. Normalize cache keys where safe (e.g., prompt prefixes).',
      '3. Separate caches by class (small hot cache vs large cold cache).',
      '4. Add admission control: do not admit huge items that evict everything else unless needed.',
      '',
      '---',
      '',
      '## 25.7 Silent Evaluation Regressions',
      '',
      '### What it looks like',
      '',
      '- The system "works" (no 500s) but users complain about quality.',
      '- A model/prompt change slowly degrades outcomes over days.',
      '',
      '### Why it happens',
      '',
      '- No regression test suite for semantic quality.',
      '- Metrics tracked are only technical (latency, error rate) not task success.',
      '- Evaluation dataset does not represent real traffic.',
      '',
      '### Detection signals',
      '',
      '- User feedback changes (thumbs down, re-ask rate)',
      '- Drift in output characteristics (length, refusal rate, tool call rate)',
      '- Sampling-based LLM judge scores trending down',
      '',
      '### Mitigations',
      '',
      '1. Maintain a golden dataset and run it on every change.',
      '2. Track slice metrics (by cohort, language, task type).',
      '3. Use shadow deployments: run the new system in parallel and compare before shipping.',
      '4. Define quality SLOs (not just latency SLOs).',
      '',
      '---',
      '',
      '## 25.8 Prompt Drift',
      '',
      '### What it looks like',
      '',
      '- A prompt that used to work no longer works after a model update.',
      '- The model starts ignoring certain instructions.',
      '',
      '### Why it happens',
      '',
      '- Model behavior changes with version updates.',
      '- Prompt accumulation: multiple teams edit the prompt without a clear spec.',
      '- Hidden dependency on a particular phrasing that was never tested.',
      '',
      '### Detection signals',
      '',
      '- Drop in schema pass rate or tool-call validity after a model version change',
      '- Output length distribution shifts',
      '- Refusal rate changes unexpectedly',
      '',
      '### Mitigations',
      '',
      '1. Version prompts and treat them like code.',
      '2. Keep prompts small and modular; remove dead instructions.',
      '3. Run regression tests when changing model versions.',
      '4. Use explicit validators rather than relying on fragile phrasing.',
      '',
      '---',
      '',
      '## 25.9 Race Conditions',
      '',
      '### What it looks like',
      '',
      '- The model makes decisions based on stale state (e.g., old user settings).',
      '- Tool calls happen in the wrong order or use inconsistent versions of data.',
      '- Duplicate side effects (two payments, two emails).',
      '',
      '### Why it happens',
      '',
      '- Concurrent tool calls without proper coordination.',
      '- Retried requests without idempotency.',
      '- Eventually consistent data stores used as if they were strongly consistent.',
      '',
      '### Detection signals',
      '',
      '- Duplicate side-effect events with same logical request id',
      '- Inconsistent tool call sequences in traces',
      '- Increased conflict errors or version mismatches',
      '',
      '### Mitigations',
      '',
      '1. Use idempotency keys for side effects.',
      '2. Use optimistic concurrency (version checks) when updating state.',
      '3. Serialize operations that must be ordered (or use a workflow engine).',
      '4. Log a single request trace that includes all tool calls and their inputs/outputs.',
      '',
      '---',
      '',
      '## 25.10 Cascading Failures',
      '',
      '### What it looks like',
      '',
      '- A single dependency slows down, then everything times out.',
      '- Retries amplify load and take down the provider.',
      '- Queueing explodes; tail latency goes vertical.',
      '',
      '### Why it happens',
      '',
      '- No circuit breakers or bulkheads.',
      '- Aggressive retries with synchronized backoff (thundering herd).',
      '- Shared bottlenecks (one vector DB, one provider quota) without prioritization.',
      '',
      '### Detection signals',
      '',
      '- Latency increases with rising concurrency (queueing)',
      '- Retry rate spikes',
      '- Error rate spikes after latency spike (timeout cascade)',
      '',
      '### Mitigations',
      '',
      '1. Circuit breakers and timeouts at every dependency boundary.',
      '2. Retries with exponential backoff and jitter, bounded by a total time budget.',
      '3. Rate limiting and load shedding by priority class.',
      '4. Graceful degradation: disable expensive features under stress.',
      '',
      '### Postmortem-style example',
      '',
      '```text',
      'Incident: cascading outage during traffic spike',
      'Impact: 18% requests failed; p95 latency exceeded 20s for 35 minutes',
      '',
      'Sequence:',
      '- traffic spike increases concurrent requests',
      '- vector DB latency increases; requests wait',
      '- app times out and retries; load increases further',
      '- model provider quota hits; more errors trigger more retries',
      '- system enters retry storm',
      '',
      'Fixes:',
      '- add circuit breaker on retrieval',
      '- cap retries by total time budget',
      '- shed low-priority traffic when queue length rises',
      '- add degraded mode without retrieval for non-critical queries',
      '```',
      '',
      '---',
      '',
      '## Production Readiness Checklist (AI-Specific)',
      '',
      'Use this checklist before launch:',
      '',
      '1. **Budgets**: max tokens, max tool calls, max agent steps, max wall-clock time.',
      '2. **Validation**: schema validation for structured outputs; tool-call validation; safety checks.',
      '3. **Idempotency**: every side-effect tool has idempotency keys.',
      '4. **Timeouts**: per dependency and end-to-end time budget.',
      '5. **Retries**: classified (retryable vs not), bounded, with jitter.',
      '6. **Circuit breakers**: on slow/down dependencies (retrieval, tools, provider).',
      '7. **Degradation**: feature flags and a clear ladder of reduced modes.',
      '8. **Observability**: traces that include prompt version, model version, retrieval ids, tool calls, validator outcomes.',
      '9. **Evaluation**: golden dataset + canary tests + monitoring for semantic quality drift.',
      '10. **Security**: tool sandboxing, permission checks, prompt injection defenses, PII handling.',
      '',
      '---',
      '',
      '## Incident Response: What To Capture',
      '',
      'When an incident happens, you want a complete trace for representative failing requests:',
      '',
      '- User input (redacted as needed)',
      '- Prompt version and rendered prompt (or prompt hash + reconstruction path)',
      '- Model version, parameters, and output token counts',
      '- Retrieval query, top-k results (ids, scores, timestamps), and packed context',
      '- Tool calls (name, args, result, latency, error type)',
      '- Validator outcomes (schema pass/fail, safety checks)',
      '- Degraded-mode state (which ladder rung)',
      '',
      'Without these artifacts, postmortems turn into arguments instead of learning.',
      '',
      '---',
      '',
      '## Exercises',
      '',
      '1. Pick one failure mode and write a runbook: detection, immediate mitigation, longer-term fix, and how to verify recovery.',
      '2. Design budgets for an agentic workflow: step cap, tool cap, token cap, and wall-clock cap. Explain which user experience you choose when caps are hit.',
      '3. Create three alerts that would have caught the cascading failure example earlier. Specify the metrics and thresholds.',
      '4. Build a small "failure injection" plan: simulate retrieval down, tool timeout, and provider rate limit. What should the user see?',
      '',
      '---',
      '',
      '## Summary',
      '',
      '- AI systems fail both technically (timeouts, 500s) and semantically (plausible wrong answers).',
      '- The most common production failures come from unbounded work, missing validators, and missing dependency protection (timeouts, circuit breakers).',
      '- Treat tool calls like a dangerous API: validate arguments, require confirmations, and enforce idempotency.',
      '- Invest in observability that captures intermediate artifacts (retrieval results, packed context, tool traces). That is the difference between guessing and debugging.',
      '',
    ].join('\n'),
  },
  {
    slug: ['handbook', 'part-ix-failure-engineering', 'chapter-26-production-case-studies'],
    title: 'Chapter 26 - Production Case Studies',
    description:
      'Publicly-inferable reference architectures for modern AI products, plus real-world infrastructure patterns and postmortem-style case studies.',
    group: partIXGroup,
    toc: [
      'How To Read These Case Studies',
      'A Reference Architecture You Can Map To Any Product',
      '26.1 ChatGPT-Style Assistant (Reference Architecture)',
      '26.2 Claude-Style Assistant (Reference Architecture)',
      '26.3 Cursor-Style Coding Assistant (Reference Architecture)',
      '26.4 GitHub Copilot-Style Suggestions (Reference Architecture)',
      '26.5 Perplexity-Style Answer + Search (Reference Architecture)',
      '26.6 Windsurf-Style Agentic IDE (Reference Architecture)',
      '26.7 OpenHands-Style Autonomous Agent (Reference Architecture)',
      '26.8 Real-World AI Infrastructure Patterns',
      'Production Checklist: Launching a Complex AI Feature',
      'Exercises',
      'Summary',
    ],
    body: [
      '# Chapter 26 - Production Case Studies',
      '',
      'Students often want the "real architecture" of popular AI products.',
      '',
      'But here is the constraint: most production details are not fully public, and private implementation details change frequently.',
      '',
      'So this chapter does something more useful:',
      '',
      '- It gives you **reference architectures** that explain how these products are typically built, based on publicly known behaviors and common engineering patterns.',
      '- It highlights **design tensions** (latency vs quality, safety vs capability, cost vs consistency).',
      '- It maps each product type to the same underlying building blocks so you can apply the lessons to your own systems.',
      '',
      'You should treat this chapter as:',
      '',
      '- a set of strong hypotheses and patterns that are widely used in production',
      '- a vocabulary for design reviews',
      '- a guide to "what you must build around the model" to ship safely',
      '',
      '---',
      '',
      '## How To Read These Case Studies',
      '',
      'For each case study, we will cover:',
      '',
      '- User experience and product constraints',
      '- Likely system components (model gateway, retrieval, tools, safety, evaluation)',
      '- Failure modes and mitigations',
      '- What you can copy as a pattern',
      '',
      'The point is not to imitate a brand. The point is to understand the architecture class.',
      '',
      '---',
      '',
      '## A Reference Architecture You Can Map To Any Product',
      '',
      'Most modern AI products can be described with this pipeline:',
      '',
      '```text',
      'Client UI',
      '  |',
      '  v',
      'API gateway (auth, rate limits, routing)',
      '  |',
      '  v',
      'Orchestrator (prompt builder, retrieval, tool planner, validators)',
      '  |',
      '  +--> Retrieval (vector DB + reranking + freshness + permissions)',
      '  |',
      '  +--> Tools (side-effecting APIs, read-only APIs, workflow engine)',
      '  |',
      '  +--> Safety (policy checks, prompt injection defenses)',
      '  |',
      '  v',
      'Model runtime (API model or self-hosted)',
      '  |',
      '  v',
      'Post-processing (schema validation, citations, redaction)',
      '  |',
      '  v',
      'Logging + traces + evaluation signals',
      '```',
      '',
      'Different products emphasize different parts:',
      '',
      '- Search-first products emphasize retrieval and citations.',
      '- Coding assistants emphasize local context ingestion and IDE tool integration.',
      '- Agentic systems emphasize budgets, termination conditions, and tool safety.',
      '',
      '---',
      '',
      '## 26.1 ChatGPT-Style Assistant (Reference Architecture)',
      '',
      '### Product constraints',
      '',
      '- General-purpose tasks across many domains.',
      '- Conversational memory and long context.',
      '- Streaming UX (time-to-first-token matters).',
      '- Safety and policy enforcement at scale.',
      '',
      '### Reference architecture',
      '',
      'A ChatGPT-style assistant commonly has:',
      '',
      '- Conversation store (messages, summaries, user preferences)',
      '- Context builder (selects relevant conversation, tool results, and optionally retrieved docs)',
      '- Tool calling (for browsing, code execution, account queries, etc.) with strict allow-lists',
      '- Safety checks (pre and post generation)',
      '- Model routing (different models for different tasks, or different modes)',
      '',
      '### Failure modes and mitigations',
      '',
      '- Prompt injection and tool misuse: mitigated via permissions, sandboxing, and confirmation gates.',
      '- Hallucination on factual queries: mitigated via retrieval/citations and refusal policies when evidence is weak.',
      '- Cost blowups from long conversations: mitigated via summarization, context budgets, and output caps.',
      '',
      '### Pattern you can copy',
      '',
      '- Treat the assistant as an orchestrated pipeline with budgets and validators, not "call model and hope."',
      '',
      '---',
      '',
      '## 26.2 Claude-Style Assistant (Reference Architecture)',
      '',
      '### Product constraints',
      '',
      '- Strong emphasis on instruction-following and safe behavior.',
      '- Long documents and careful summarization.',
      '',
      '### Reference architecture',
      '',
      'A Claude-style assistant (as an architecture class) often emphasizes:',
      '',
      '- Clear system policies and consistent refusal behavior',
      '- Strong prompting discipline (explicit constraints and boundaries)',
      '- Retrieval and document handling pipelines for long inputs',
      '- Evaluation focused on safety and helpfulness tradeoffs',
      '',
      '### Pattern you can copy',
      '',
      '- Design refusal as a first-class output, not as a crash or an apology.',
      '',
      '---',
      '',
      '## 26.3 Cursor-Style Coding Assistant (Reference Architecture)',
      '',
      'This section describes a modern IDE coding assistant architecture, not any private implementation details.',
      '',
      '### Product constraints',
      '',
      '- Must be fast enough to feel interactive while you type.',
      '- Must use local code context safely (permissions, secrets).',
      '- Must produce changes that compile and pass tests.',
      '- Must integrate with developer workflows (diffs, apply patches, run commands).',
      '',
      '### Reference architecture',
      '',
      '```text',
      'IDE extension',
      '  - captures open files, selection, diagnostics, git diff',
      '  - asks user for confirmation on risky actions',
      '  |',
      '  v',
      'Context indexer',
      '  - builds embeddings for repo files',
      '  - supports semantic search for relevant code',
      '  |',
      '  v',
      'Orchestrator',
      '  - prompt builder + retrieval + tool harness',
      '  - validators: "does patch apply?", "does it compile?", "tests?"',
      '  |',
      '  v',
      'Model (often routed by task type)',
      '```',
      '',
      '### Key patterns',
      '',
      '- Use structured outputs for patches (diff format, file edits).',
      '- Validate changes with deterministic tools (typecheck, unit tests) where possible.',
      '- Keep a strict action boundary: model proposes, system validates and executes with user consent.',
      '',
      '### Postmortem-style failure example',
      '',
      '```text',
      'Incident: assistant broke builds across many repos',
      'Impact: developer trust drop; increased support tickets',
      '',
      'Root cause:',
      '- patch generator changed formatting rules; validator did not run in some paths',
      '- system applied changes without running a compile check',
      '',
      'Fixes:',
      '- always run at least a fast compile/typecheck before suggesting "done"',
      '- add schema validation for patch format',
      '- add rollback: "revert last patch" button in UI',
      '```',
      '',
      '---',
      '',
      '## 26.4 GitHub Copilot-Style Suggestions (Reference Architecture)',
      '',
      '### Product constraints',
      '',
      '- Ultra-low latency suggestions (typing loop).',
      '- Small context window (nearby code) but strong relevance.',
      '- Strong privacy constraints (do not leak repo contents).',
      '',
      '### Reference architecture',
      '',
      'A suggestion engine typically emphasizes:',
      '',
      '- Lightweight context selection (current file + nearby symbols)',
      '- Caching and prefix reuse (many similar prompts while typing)',
      '- Aggressive output length caps (short completions)',
      '- Safety filters to avoid generating sensitive strings (keys, secrets) and to respect policies',
      '',
      '### Pattern you can copy',
      '',
      '- Optimize time-to-first-token and keep the request small. Suggestions are a different architecture class than chat.',
      '',
      '---',
      '',
      '## 26.5 Perplexity-Style Answer + Search (Reference Architecture)',
      '',
      'This section describes an "answer engine" architecture class: search + citations + synthesis.',
      '',
      '### Product constraints',
      '',
      '- Must provide citations and source transparency.',
      '- Must deal with changing information (freshness matters).',
      '- Must be robust to adversarial or low-quality sources.',
      '',
      '### Reference architecture',
      '',
      '```text',
      'User query',
      '  -> web search / index search',
      '  -> dedupe and filter sources',
      '  -> extract passages',
      '  -> rerank by relevance + freshness + trust signals',
      '  -> generate answer with citations',
      '  -> verify citations exist and map to claims',
      '```',
      '',
      '### Failure modes and mitigations',
      '',
      '- Citation laundering: mitigate by claim-to-evidence verification and requiring citations per paragraph.',
      '- Freshness errors: mitigate with timestamp-aware ranking and explicit "as of" phrasing for time-sensitive queries.',
      '- Source quality: mitigate with allow-lists, reputation signals, and user-visible source lists.',
      '',
      '---',
      '',
      '## 26.6 Windsurf-Style Agentic IDE (Reference Architecture)',
      '',
      'Agentic IDE assistants are a step beyond suggestions: they plan, execute tools, and iterate.',
      '',
      '### Product constraints',
      '',
      '- Must coordinate multi-step workflows (search code, edit, run tests, iterate).',
      '- Must avoid runaway loops and uncontrolled tool actions.',
      '',
      '### Reference architecture',
      '',
      '- Planner: breaks a goal into steps',
      '- Executor: runs tools (search, edit, run commands) under strict policies',
      '- Verifier: runs deterministic checks (tests, linters) and summarizes results',
      '- Budget controller: caps steps, tool calls, and wall time',
      '',
      '### Pattern you can copy',
      '',
      '- Treat "agent" as a workflow engine with explicit budgets and termination states, not as a magical loop.',
      '',
      '---',
      '',
      '## 26.7 OpenHands-Style Autonomous Agent (Reference Architecture)',
      '',
      'Autonomous agents attempt longer tasks with less user interaction. That increases the blast radius.',
      '',
      '### Product constraints',
      '',
      '- Long-running tasks (minutes to hours).',
      '- Many tool calls and state changes.',
      '- Higher risk of compounding mistakes.',
      '',
      '### Reference architecture',
      '',
      'A safer autonomous agent design uses:',
      '',
      '- Read-only tools by default; require explicit escalation for write actions',
      '- A workspace sandbox (filesystem, network) with tight permissions',
      '- A checkpoint system: record state so you can resume and roll back',
      '- A verifier that runs tests and checks invariants after changes',
      '',
      '### Failure modes to expect',
      '',
      '- Infinite loops (must be bounded)',
      '- Tool misuse (must be validated)',
      '- Silent regression (must run tests)',
      '- Data exfiltration risk (must sandbox)',
      '',
      '---',
      '',
      '## 26.8 Real-World AI Infrastructure Patterns',
      '',
      'These patterns show up across many teams because they solve real production problems.',
      '',
      '### Pattern 1: Model Gateway',
      '',
      'A model gateway sits between product code and model providers/self-hosted runtimes.',
      '',
      'It typically provides:',
      '',
      '- authentication and key management',
      '- rate limiting (requests and tokens)',
      '- routing across models/providers',
      '- consistent logging and tracing',
      '- retry policies and circuit breakers',
      '',
      '### Pattern 2: Prompt Registry + Versioning',
      '',
      'Treat prompts as versioned artifacts with:',
      '',
      '- owners and change history',
      '- evaluation results attached to versions',
      '- rollback to a known-good prompt',
      '',
      '### Pattern 3: Retrieval Service as a Product',
      '',
      'Make retrieval a first-class service with:',
      '',
      '- ingestion pipelines and backfills',
      '- index versioning',
      '- permission enforcement',
      '- freshness tracking',
      '- evaluation metrics (recall@k, groundedness)',
      '',
      '### Pattern 4: Guardrails as Deterministic Gates',
      '',
      'Combine the model with deterministic checks:',
      '',
      '- schema validation',
      '- policy rules (allow/deny)',
      '- tool-call allow-lists',
      '- idempotency enforcement',
      '',
      '### Pattern 5: Shadow + Canary + Gradual Rollouts',
      '',
      'Because semantic regressions are common, teams use:',
      '',
      '- shadow deployments to compare outputs offline',
      '- canary sets (must-pass examples)',
      '- gradual rollouts with monitoring and rollback',
      '',
      '### Pattern 6: "Make It Observable" by Logging Intermediate Artifacts',
      '',
      'When a user reports "it was wrong," you need to know:',
      '',
      '- what the model saw (rendered prompt)',
      '- what was retrieved (ids + text + scores)',
      '- what tools returned',
      '- what validators decided',
      '',
      'Without these, you are debugging blind.',
      '',
      '---',
      '',
      '## Production Checklist: Launching a Complex AI Feature',
      '',
      '1. Define success metrics and a golden evaluation set.',
      '2. Implement strict budgets (tokens, tools, steps, time).',
      '3. Validate structured outputs and tool calls.',
      '4. Add idempotency and confirmation gates for side effects.',
      '5. Instrument traces with intermediate artifacts.',
      '6. Implement circuit breakers and graceful degradation.',
      '7. Create an incident playbook and on-call ownership.',
      '8. Roll out gradually with rollback.',
      '',
      '---',
      '',
      '## Exercises',
      '',
      '1. Pick one product class above (search engine, coding assistant, chat assistant). Draw its reference architecture and label where you would put budgets, validators, and safety gates.',
      '2. Write a postmortem for a hypothetical incident: stale retrieval caused incorrect policy advice. Include impact, root cause, detection gap, and fixes.',
      '3. Design a model gateway interface for your app: what logs, limits, and routing decisions should it own?',
      '4. Choose one infrastructure pattern and propose how you would evaluate it (what metrics prove it helped?).',
      '',
      '---',
      '',
      '## Summary',
      '',
      '- Popular AI products map to a small set of architecture classes (chat assistants, search+answer engines, coding assistants, autonomous agents).',
      '- The model is only one component; production systems require orchestration, retrieval, tool safety, budgets, validators, and observability.',
      '- Reference architectures let you borrow proven patterns without relying on private claims.',
      '- The most reusable patterns are: model gateways, prompt versioning, retrieval services, deterministic guardrails, gradual rollouts, and logging intermediate artifacts for debuggability.',
      '',
    ].join('\n'),
  },
];

export default part07StrategyFailureCaseStudiesPages;

