import type { DocPage } from '../pages';

function md(lines: string[]) {
  return lines.join('\n');
}

const appendixACoreConcepts: DocPage = {
  slug: ['appendices', 'appendix-a-core-concepts'],
  title: 'Appendix A: Core Concepts',
  description: 'Definitions and mental models for the concepts that show up everywhere else in the handbook.',
  group: 'Appendices',
  toc: [
    'How To Use This Appendix',
    'Transformer Architecture',
    'Attention Mechanism',
    'Embedding Spaces',
    'Tokenization Algorithms',
    'Positional Encoding',
    'Mixture of Experts (MoE)',
    'Context Windows',
    'Quick Reference Tables',
  ],
  body: md([
    '# Appendix A: Core Concepts',
    '',
    'This appendix is a vocabulary and mental-model refresher. Use it when a chapter assumes you already know a term.',
    '',
    'Cross-chapter map:',
    '- Tokenization and context limits: see Chapter 3 (Tokenization) and Chapter 2 (Context Window Management).',
    '- KV cache and attention memory behavior: see Chapter 4 (KV Cache) and Chapter 5 (Efficient Inference).',
    '- Embeddings and retrieval: see Chapter 12 (Embeddings, Vector Databases) and Chapter 14 (Grounding, Hallucination Detection).',
    '',
    '## How To Use This Appendix',
    '',
    'For each concept you get:',
    '- A clear definition',
    '- A simple mental model',
    '- What engineers usually get wrong',
    '- What to measure or watch in production',
    '',
    '## Transformer Architecture',
    '',
    '**Definition.** A transformer is a neural network architecture built around *attention* and *feed-forward blocks*, stacked many times.',
    '',
    '**Mental model.** Think of a transformer layer as two big steps:',
    '1. **Mix information across positions** (attention: each token looks at other tokens).',
    '2. **Transform each position independently** (MLP/feed-forward: non-linear feature building).',
    '',
    'Most modern LLMs use a decoder-only transformer (a stack of self-attention + MLP blocks) trained to predict the next token.',
    '',
    '**Where it shows up.**',
    '- Latency/throughput: attention dominates compute and memory as context grows (see Chapters 4-6).',
    '- Reliability: models are trained on next-token prediction, so they can be confident and wrong without grounding (see Chapter 14).',
    '',
    '**Common confusion.** "The model understands meaning like a database." It does not. It learns statistical structure and patterns of token sequences. Retrieval, tools, and verification are how you make outputs dependable.',
    '',
    '## Attention Mechanism',
    '',
    '**Definition.** Attention is a weighted aggregation: each token position produces weights over other positions, then mixes their representations.',
    '',
    '**Mental model.** A token asks: "Which earlier tokens are relevant to me right now, and how much?"',
    '',
    '**Engineer-useful view (Q/K/V).**',
    '- **Query (Q):** what this position is looking for',
    '- **Key (K):** what each position offers',
    '- **Value (V):** the information you actually mix in',
    '',
    'In practice, you mostly care about two production consequences:',
    '1. **Memory:** serving keeps keys/values for past tokens (KV cache).',
    '2. **Cost growth:** longer prompts cost more compute and more memory.',
    '',
    '**What people get wrong.**',
    '- "Attention is interpretability." Attention weights are not a reliable explanation of model reasoning.',
    '- "Longer context always helps." Past a point you get distraction, latency, and cost with diminishing returns (see Chapter 2.5-2.8).',
    '',
    '## Embedding Spaces',
    '',
    '**Definition.** An embedding is a vector (a list of numbers) that represents text, images, or other objects so that semantic similarity can be computed by distance (often cosine similarity).',
    '',
    '**Mental model.** The embedding model maps an item to a point in space. Similar items land near each other. Retrieval systems do "find neighbors" and return the best matches.',
    '',
    '**What embeddings are good for.**',
    '- Semantic search (RAG)',
    '- Deduplication / clustering',
    '- Routing and intent classification',
    '',
    '**What embeddings are not.**',
    '- A ground-truth representation of meaning (bias and blind spots exist)',
    '- A guarantee of factuality (you can retrieve plausible-but-wrong chunks)',
    '',
    '**Practical tips (high signal).**',
    '- Normalize: many vector DBs assume cosine similarity; check whether you need unit normalization.',
    '- Chunking matters as much as the embedding model (see Chapter 12.2).',
    '- Use filters/metadata to prevent cross-domain confusion (see Chapter 12.5).',
    '',
    '## Tokenization Algorithms',
    '',
    '**Definition.** Tokenization turns text into a sequence of discrete token IDs. Models operate on tokens, not characters.',
    '',
    '**Why it matters.** Tokenization affects:',
    '- context window usage (how many tokens your prompt becomes)',
    '- cost (tokens are the unit of billing in many APIs)',
    '- latency (more tokens means longer prefill and decode)',
    '',
    '**Common tokenizers (simplified).**',
    '',
    '| Tokenizer family | Core idea | Typical strength | Typical weakness |',
    '|---|---|---|---|',
    '| BPE (byte-pair encoding) | Merge frequent byte/char pairs into subwords | Good compression, flexible | Can split unexpectedly; token counts vary by language |',
    '| WordPiece | Likelihood-based subword building | Often stable for common words | Still subword splits; OOV handled via pieces |',
    '| Unigram (SentencePiece) | Probabilistic subword set; choose best segmentation | Good for multilingual | Can be less intuitive; depends on training data |',
    '| Byte-level BPE | Operate on bytes to avoid unknowns | Robust to weird text | Can increase tokens for some scripts |',
    '',
    '**Engineer pitfall.** "The user typed 2,000 characters so it is ~2,000 tokens." Token counts are not character counts. Always measure with the model\'s tokenizer (see Chapter 3.1).',
    '',
    '## Positional Encoding',
    '',
    '**Definition.** A transformer needs a way to represent order (position) because attention alone is permutation-invariant. Positional encodings inject information about token index so the model can learn sequence structure.',
    '',
    '**Mental model.** Content tells you *what* a token is. Position tells you *where* it is relative to others.',
    '',
    '**Practical consequence.** Position handling influences long-context behavior and extrapolation. Many modern variants exist; as an app engineer you mostly experience this indirectly as:',
    '- how quality changes with very long contexts',
    '- whether the model is stable when you stuff huge documents in the prompt',
    '',
    '## Mixture of Experts (MoE)',
    '',
    '**Definition.** An MoE model routes tokens through a small subset of many available "expert" sub-networks. This increases parameter count without increasing compute proportionally (if only a few experts are active per token).',
    '',
    '**Mental model.** Instead of one big MLP everywhere, you have many specialized MLPs, and a router chooses which ones to use per token.',
    '',
    '**Why engineers care.**',
    '- You can get higher quality per unit of inference FLOPs.',
    '- Serving can be trickier: expert parallelism, load balancing, and memory layout matter.',
    '',
    '**Failure modes you might see.**',
    '- Uneven expert usage (hot experts) leading to bottlenecks.',
    '- Slightly different behavior between batches if routing is sensitive.',
    '',
    '## Context Windows',
    '',
    '**Definition.** The context window is the maximum number of tokens the model can condition on (prompt + generated tokens).',
    '',
    '**Mental model.** The model is not "reading a file"; it is conditioning next-token probabilities on a sliding set of tokens.',
    '',
    '**Engineer checklist.**',
    '- Separate **prefill cost** (processing the prompt) from **decode cost** (generating output).',
    '- Budget tokens for: instructions, conversation history, retrieved context, tool outputs, and the model\'s own answer.',
    '- Plan a truncation strategy: what gets dropped first when you run out (see Chapter 2.5).',
    '',
    '**Important nuance.** Even if a model supports a large context, quality can degrade with extremely long prompts. RAG, summarization, and context packing exist for a reason (see Chapters 12-13).',
    '',
    '## Quick Reference Tables',
    '',
    '| Concept | In one sentence | Where you feel it in practice |',
    '|---|---|---|',
    '| Attention | Mix information across tokens using learned weights | KV cache memory, long-context cost |',
    '| KV cache | Stored keys/values for past tokens | GPU memory, throughput, batch size |',
    '| Embeddings | Vectors for semantic similarity search | RAG quality/latency, retrieval failures |',
    '| Tokenization | Map text to token IDs | Cost, latency, truncation bugs |',
    '| Context window | Token budget for prompt + completion | Truncation policy, RAG packing |',
    '',
    'Minimal math (optional): dot product similarity is the workhorse for both attention and many embedding searches.',
    '',
    '```text',
    'dot(a, b) = sum_i a[i] * b[i]',
    'cosine(a, b) = dot(a, b) / (||a|| * ||b||)',
    '```',
  ]),
};

const appendixBEngineeringPatterns: DocPage = {
  slug: ['appendices', 'appendix-b-engineering-patterns'],
  title: 'Appendix B: Engineering Patterns',
  description: 'Repeatable patterns for prompts, tools, RAG, agents, routing, retries, and caching.',
  group: 'Appendices',
  toc: [
    'Pattern Format',
    'Prompt Patterns',
    'Tool Calling Patterns',
    'RAG Patterns',
    'Agent Patterns',
    'Routing Patterns',
    'Retry Patterns',
    'Caching Patterns',
    'Comparison Charts',
  ],
  body: md([
    '# Appendix B: Engineering Patterns',
    '',
    'These are practical patterns you can copy into designs and code reviews. Each pattern includes: when to use it, how to implement it, and what breaks.',
    '',
    'Cross-chapter map:',
    '- Prompts and context: Chapter 2 (Context Engineering).',
    '- Structured outputs and repair: Chapter 8 (Structured Outputs).',
    '- Function calling and tool contracts: Chapter 9 (Function Calling).',
    '- Agent loop control: Chapter 10 (Agent Engineering).',
    '- Routing: Chapter 11 (Model Routing).',
    '- Retries/timeouts/circuit breakers: Chapter 19 (Reliability Engineering).',
    '',
    '## Pattern Format',
    '',
    'Use this as a standard template in docs/PRs:',
    '',
    '```text',
    'Name:',
    'Use when:',
    'Mechanism:',
    'Success signals (metrics):',
    'Failure modes:',
    'Mitigations:',
    'Related chapters:',
    '```',
    '',
    '## Prompt Patterns',
    '',
    '### Pattern: Instruction Sandwich',
    '',
    'Name: Instruction Sandwich',
    'Use when: You provide long context (RAG, documents) and still need stable behavior.',
    'Mechanism: Put compact rules before and after the context so the model "sees" them near the end too.',
    'Success signals: Lower policy drift; fewer ignored constraints.',
    'Failure modes: Rules still overridden by conflicting context; over-long prompts.',
    'Mitigations: Tighten rules; remove irrelevant context; add structured outputs (Chapter 8).',
    'Related chapters: 2.4, 2.7, 12.7, 8.3.',
    '',
    'Example (structure only):',
    '```text',
    '[SYSTEM/DEVELOPER RULES]',
    '[USER REQUEST]',
    '[RETRIEVED CONTEXT]',
    '[FINAL REMINDER: OUTPUT FORMAT + DO NOTs]',
    '```',
    '',
    '### Pattern: Output Contract Block',
    '',
    'Name: Output Contract Block',
    'Use when: Downstream code consumes the response.',
    'Mechanism: Specify a single unambiguous output format and add a "no extra keys/text" rule.',
    'Success signals: Parser success rate; fewer repair loops.',
    'Failure modes: Model adds commentary; partial JSON; wrong types.',
    'Mitigations: JSON/grammar constrained generation; schema validation; targeted retries (Chapter 8).',
    '',
    '## Tool Calling Patterns',
    '',
    '### Pattern: Validate-Then-Execute',
    '',
    'Name: Validate-Then-Execute',
    'Use when: Tool execution has side effects (writes, payments, emails) or can leak data.',
    'Mechanism: Split into two steps: (1) propose arguments, (2) validate against allowlists/policy, (3) execute.',
    'Success signals: No policy-violating tool calls; low incident rate.',
    'Failure modes: Prompt injection pushes dangerous args; tool schema too permissive.',
    'Mitigations: Strict schemas; server-side validation; approval gates; sandboxing (Chapters 9, 20-21).',
    '',
    'Sketch:',
    '```json',
    '{',
    '  "step": "propose_tool_call",',
    '  "tool": "send_email",',
    '  "args": { "to": "...", "subject": "...", "body": "..." }',
    '}',
    '```',
    '',
    '### Pattern: Idempotency Keys for Tools',
    '',
    'Name: Idempotency Keys',
    'Use when: Retries are possible and side effects must not duplicate.',
    'Mechanism: Every side-effect tool call includes an idempotency key derived from (request_id, tool_name, semantic intent).',
    'Success signals: Duplicate-free retries; safe timeouts.',
    'Failure modes: Non-deterministic keys; key collisions; partial failures.',
    'Mitigations: Store tool call ledger; return previous result on repeat key (Chapter 9.5, 19.1-19.3).',
    '',
    '## RAG Patterns',
    '',
    '### Pattern: Retrieval First, Then Reason',
    '',
    'Name: Retrieval First, Then Reason',
    'Use when: The answer depends on external knowledge and hallucination risk is high.',
    'Mechanism: Force retrieval before allowing final answer; require citations/attribution fields in output.',
    'Success signals: Higher grounding score; fewer unsupported claims.',
    'Failure modes: Retrieval returns irrelevant context; the model answers anyway.',
    'Mitigations: Add "abstain if not found"; rerank; query rewriting; fallback to tool search (Chapters 12-14).',
    '',
    '### Pattern: Context Packing With Budget',
    '',
    'Name: Context Packing With Budget',
    'Use when: You retrieve many chunks but have a strict token budget.',
    'Mechanism: Rank chunks, then pack until budget; prefer diversity (avoid near-duplicates).',
    'Success signals: Better answer quality at same token cost.',
    'Failure modes: Overpacking duplicates; missing key chunk; prompt overflow.',
    'Mitigations: Deduplicate by embedding similarity; enforce per-source caps; compress long chunks (Chapters 12.7, 13.2, 2.5).',
    '',
    '## Agent Patterns',
    '',
    '### Pattern: Budgeted Tool Loop',
    '',
    'Name: Budgeted Tool Loop',
    'Use when: You have an agent that can iterate (search, plan, execute).',
    'Mechanism: Enforce budgets for steps, tools, tokens, and time; define termination conditions explicitly.',
    'Success signals: No infinite loops; predictable cost; stable latency.',
    'Failure modes: The agent keeps exploring; "one more tool call" behavior.',
    'Mitigations: Hard caps; early-stop heuristics; "final answer required" gate (Chapter 10.7-10.9).',
    '',
    '### Pattern: Decompose-Then-Verify',
    '',
    'Name: Decompose-Then-Verify',
    'Use when: Tasks have hidden constraints (parsing, calculations, policy).',
    'Mechanism: Separate planning from execution and add a verification pass that checks the output contract.',
    'Success signals: Fewer wrong-but-confident results; fewer malformed outputs.',
    'Failure modes: Verification is too weak; verifier shares the same blind spots.',
    'Mitigations: Use deterministic checks (schemas, unit tests); external validators; adversarial test cases (Chapters 8, 15-16).',
    '',
    '## Routing Patterns',
    '',
    '### Pattern: Cheap Model First, Escalate on Uncertainty',
    '',
    'Name: Escalate on Uncertainty',
    'Use when: Many requests are easy but a tail requires high quality.',
    'Mechanism: Start with a cheaper/faster model; upgrade when signals indicate uncertainty (low confidence, high policy risk, parse failures).',
    'Success signals: Lower cost for same quality; stable tail latency.',
    'Failure modes: Wrong confidence signal; too many escalations.',
    'Mitigations: Calibrate triggers with offline evaluation; add guardrails; track escalation rate (Chapter 11).',
    '',
    '## Retry Patterns',
    '',
    '### Pattern: Retry Only The Smallest Failing Unit',
    '',
    'Name: Smallest-Unit Retry',
    'Use when: Full pipeline retries are expensive or unsafe.',
    'Mechanism: Retry only the step that failed (parse, tool call, retrieval), not the whole user workflow.',
    'Success signals: Lower cost; fewer duplicated side effects.',
    'Failure modes: Hidden coupling between steps; stale context.',
    'Mitigations: Make step inputs explicit; log artifacts; use idempotency keys (Chapters 8-9, 19).',
    '',
    '### Pattern: Retry With Jittered Backoff',
    '',
    'Name: Jittered Backoff',
    'Use when: You are hitting transient failures (rate limits, network).',
    'Mechanism: Exponential backoff plus randomness (jitter) to avoid thundering herds.',
    'Success signals: Reduced retry storms; better success rate under load.',
    'Failure modes: Unbounded latency; queued requests pile up.',
    'Mitigations: Total retry budget; circuit breakers; fallbacks (Chapter 19.1-19.6).',
    '',
    '## Caching Patterns',
    '',
    '### Pattern: Cache The Deterministic Parts',
    '',
    'Name: Deterministic-Unit Cache',
    'Use when: Some steps are pure functions of their inputs (embedding generation, retrieval queries, prompt assembly).',
    'Mechanism: Cache inputs -> outputs with stable keys; separate from stochastic model outputs.',
    'Success signals: Lower latency; lower cost; fewer repeated computations.',
    'Failure modes: Cache poisoning; stale results; cache misses from unstable keys.',
    'Mitigations: Version keys; TTLs; per-tenant separation; strict validation (Chapters 18-19, 21-22).',
    '',
    '### Pattern: Semantic Cache For Responses',
    '',
    'Name: Semantic Response Cache',
    'Use when: Users ask the same question in different words and exact caching misses.',
    'Mechanism: Embed the request, cache by similarity threshold, and return cached response if it matches intent.',
    'Success signals: High hit rate with acceptable correctness.',
    'Failure modes: Wrong match returns wrong answer; privacy leaks across tenants.',
    'Mitigations: Tenant isolation; conservative thresholds; only cache low-risk answers (Chapters 12, 22).',
    '',
    '## Comparison Charts',
    '',
    '| Decision | Prefer this | When | Why |',
    '|---|---|---|---|',
    '| Prompt-only vs tool-based | Tool-based | External truth needed | Determinism and auditability |',
    '| RAG vs fine-tuning | RAG | Knowledge changes frequently | Update data without retraining |',
    '| One big agent vs small workflows | Small workflows | Predictable products | Easier evaluation and reliability |',
    '| Global retries vs step retries | Step retries | Multi-step systems | Lower cost and fewer side effects |',
  ]),
};

const appendixCChecklists: DocPage = {
  slug: ['appendices', 'appendix-c-checklists'],
  title: 'Appendix C: Checklists',
  description: 'Practical review checklists for production readiness, RAG, prompts, evaluation, security, cost, and observability.',
  group: 'Appendices',
  toc: [
    'How To Use Checklists',
    'Production Readiness Checklist',
    'RAG Checklist',
    'Prompt Review Checklist',
    'Evaluation Checklist',
    'Security Checklist',
    'Cost Optimization Checklist',
    'Observability Checklist',
    'Stop-Ship Criteria',
  ],
  body: md([
    '# Appendix C: Checklists',
    '',
    'These checklists are written to be used in real engineering workflows: design reviews, pre-launch checks, and incident postmortems.',
    '',
    'Cross-chapter map:',
    '- Reliability controls: Chapter 19.',
    '- Security controls: Chapters 20-22.',
    '- Evaluation: Chapters 15-16.',
    '- RAG: Chapters 12-14.',
    '',
    '## How To Use Checklists',
    '',
    'Checklist usage rule: treat them like unit tests. If a checkbox fails, decide explicitly whether you will fix it, accept the risk, or change the goal.',
    '',
    '## Production Readiness Checklist',
    '',
    '- [ ] Clear product contract: what the feature does, does not do, and how failure is handled.',
    '- [ ] Latency budget defined (p50/p95/p99) including tool calls, retrieval, and streaming behavior.',
    '- [ ] Cost budget defined: tokens/request, tool costs, per-tenant caps (see Chapter 18).',
    '- [ ] Safe defaults: timeouts, retries, circuit breakers, fallbacks (see Chapter 19).',
    '- [ ] Output contract enforced: schema validation + repair/retry policy (see Chapter 8).',
    '- [ ] Tool safety: allowlists, argument validation, idempotency keys (see Chapter 9, Chapter 21).',
    '- [ ] Data handling reviewed: PII, secrets, retention, logging redaction (see Chapter 21).',
    '- [ ] Evaluation plan exists: golden set + regression tests + monitoring (see Chapters 15-16).',
    '- [ ] Observability shipped: structured logs, traces, metrics, exemplars (see Chapter 17).',
    '- [ ] Incident playbook exists: rollback, degrade modes, on-call alerts (see Chapter 19.6-19.8).',
    '',
    '## RAG Checklist',
    '',
    '- [ ] Retrieval goal is explicit: freshness, coverage, citations, or personalization.',
    '- [ ] Chunking strategy chosen for the domain (see Chapter 12.2).',
    '- [ ] Embedding model evaluated on in-domain queries (see Chapter 12.3).',
    '- [ ] Metadata filters prevent cross-domain leakage (see Chapter 12.5 and Chapter 22).',
    '- [ ] Hybrid search considered (keyword + vectors) for exact-match needs (see Chapter 12.6).',
    '- [ ] Reranking plan exists for relevance (see Chapter 13.1).',
    '- [ ] Context packing has a token budget and dedup rules (see Chapter 12.7).',
    '- [ ] Freshness policy defined: indexing cadence, invalidation, staleness alerts (see Chapter 12.8).',
    '- [ ] Grounding evaluation: citation quality, hallucination rate, refusal behavior (see Chapter 14).',
    '',
    '## Prompt Review Checklist',
    '',
    '- [ ] Instructions are short, specific, and non-contradictory (see Chapter 2.3-2.4).',
    '- [ ] Output format is unambiguous and validated (see Chapter 8).',
    '- [ ] Tool usage rules are explicit: when to call tools, when not to (see Chapter 9).',
    '- [ ] Prompt avoids fragile phrasing and hidden assumptions.',
    '- [ ] Context injection risks addressed (see Chapter 20).',
    '- [ ] Prompt versioning strategy exists (see Chapter 2.10).',
    '- [ ] Prompt includes "abstain" behavior when info is missing or conflicts.',
    '',
    '## Evaluation Checklist',
    '',
    '- [ ] Golden dataset covers typical, edge, and adversarial inputs (see Chapter 15.1, 15.4).',
    '- [ ] Metrics chosen match product goals (helpfulness, correctness, grounding, latency, cost).',
    '- [ ] Regression tests run on every change (prompt, model, retrieval, tools) (see Chapter 15.3, Chapter 16).',
    '- [ ] Human evaluation rubric exists for high-stakes behavior (see Chapter 15.5).',
    '- [ ] Judge-model evaluation is calibrated and audited for bias/leakage (see Chapter 15.6).',
    '- [ ] Online monitoring detects drift: model, prompt, retrieval (see Chapter 17.7-17.9).',
    '',
    '## Security Checklist',
    '',
    '- [ ] Prompt injection threats considered for both direct and indirect inputs (see Chapter 20.1, 20.6).',
    '- [ ] System prompt and tool instructions are not exposed to untrusted content.',
    '- [ ] Tool schemas are least-privilege; argument validation is server-side (see Chapter 21.5).',
    '- [ ] Sensitive actions require confirmation / approvals (payments, deletions, emails).',
    '- [ ] Secrets never enter prompts; redaction in logs is verified (see Chapter 21.3).',
    '- [ ] Tenant isolation: caches, vector indexes, logs, and tracing are partitioned (see Chapter 22).',
    '- [ ] Sandboxing / egress controls applied to tool execution where relevant (see Chapter 21.6).',
    '',
    '## Cost Optimization Checklist',
    '',
    '- [ ] Token accounting exists per request and per feature (see Chapter 18.1-18.4).',
    '- [ ] Prompt is compact: remove duplicate instructions and irrelevant history (see Chapter 2.5-2.6).',
    '- [ ] Use smaller models where acceptable; route to larger models when needed (see Chapter 11).',
    '- [ ] Constrain outputs: cap max tokens; prefer structured outputs to reduce verbosity (see Chapter 8).',
    '- [ ] Cache deterministic steps; consider semantic caching only for low-risk answers (see Appendix B).',
    '- [ ] Retrieval tuned to retrieve fewer, better chunks (rerank + packing) (see Chapter 13).',
    '',
    '## Observability Checklist',
    '',
    '- [ ] Every request has a trace id; tool calls and retrieval appear as spans (see Chapter 17.2-17.3).',
    '- [ ] Token metrics logged: prompt tokens, completion tokens, total tokens (see Chapter 17.4).',
    '- [ ] Latency decomposed: prefill vs decode vs tool time (see Chapter 3.3-3.5, Chapter 17.5).',
    '- [ ] Error taxonomy is defined and tracked (parse errors, tool failures, retrieval misses, policy refusals).',
    '- [ ] Model/prompt/retrieval drift detectors exist (see Chapter 17.7-17.9).',
    '- [ ] Sampling/routing decisions are logged with enough context to debug (see Chapters 6 and 11).',
    '',
    '## Stop-Ship Criteria',
    '',
    'Treat these as launch blockers for most products:',
    '- Output cannot be parsed reliably (schema failures without safe fallback).',
    '- Tool calls can trigger side effects without server-side validation or idempotency protection.',
    '- Cross-tenant leakage is possible via retrieval, caching, logs, or tools.',
    '- No rollback/degrade mode exists for outages or model regressions.',
    '- No evaluation baseline exists, so you cannot detect regressions.',
  ]),
};

const appendixDCheatsheets: DocPage = {
  slug: ['appendices', 'appendix-d-cheatsheets'],
  title: 'Appendix D: Cheatsheets',
  description:
    'High-signal references for sampling, quantization, GPU memory, token accounting, embeddings, vector DBs, evaluation metrics, and failure modes.',
  group: 'Appendices',
  toc: [
    'Sampling Parameters',
    'Quantization Formats',
    'GPU Memory Reference',
    'Token Accounting',
    'Embedding Models',
    'Vector Database Comparison',
    'Evaluation Metrics',
    'Common Failure Modes',
  ],
  body: md([
    '# Appendix D: Cheatsheets',
    '',
    'This is the "open on the second monitor" appendix. It favors quick lookups and rules of thumb.',
    '',
    '## Sampling Parameters',
    '',
    'Sampling is how a model chooses the next token during decoding (see Chapter 3.6 and Chapter 6). These controls trade off determinism vs diversity.',
    '',
    '| Parameter | What it does | Typical effect | Common failure mode |',
    '|---|---|---|---|',
    '| Temperature | Scales logits before sampling | Higher -> more randomness | Too high -> incoherent; too low -> repetitive |',
    '| Top-p (nucleus) | Keep smallest set whose cumulative prob >= p | Stable diversity | Too low -> safe but bland; too high -> rambly |',
    '| Top-k | Keep only k most likely tokens | Caps tail risk | Too low -> repetitive; too high -> noisy |',
    '| Min-p | Drop tokens below a probability floor | Reduces junk tokens | Can over-prune rare correct tokens |',
    '| Beam search | Keep multiple partial hypotheses | Good for short structured decoding | Can be slow; can prefer generic sequences |',
    '',
    'Rule of thumb for product outputs:',
    '- Structured output / code generation: prefer lower randomness and strong constraints (schema/grammar).',
    '- Brainstorming / ideation: allow more diversity, but cap verbosity.',
    '',
    '## Quantization Formats',
    '',
    'Quantization is how you represent weights/activations with fewer bits to reduce memory and improve throughput (see Chapter 7).',
    '',
    '| Format | Bits | Where used | Why you care | Typical tradeoff |',
    '|---|---:|---|---|---|',
    '| FP32 | 32 | Training/reference | Highest precision | Too slow/large for many deployments |',
    '| FP16 | 16 | Inference/training | Faster, smaller | Can overflow/underflow in some ops |',
    '| BF16 | 16 | Training/inference | Better range than FP16 | Similar size; hardware-dependent |',
    '| FP8 | 8 | Advanced inference/training | Much faster on supported GPUs | Quality can drop; calibration matters |',
    '| INT8 | 8 | Inference weights/activations | Big memory savings | Needs calibration; may affect quality |',
    '| INT4 | 4 | Inference weights (common) | Very large memory savings | Larger quality hit; sensitive layers matter |',
    '',
    '## GPU Memory Reference',
    '',
    'Two big buckets in serving:',
    '- **Weights memory**: fixed per model (affected by quantization).',
    '- **KV cache memory**: grows with batch size and context length (see Chapter 4).',
    '',
    'A useful approximation for KV cache growth (order-of-magnitude planning):',
    '```text',
    'KV_cache_bytes ~= batch_size * seq_len * num_layers * 2 * hidden_size * bytes_per_element',
    '',
    '2 = keys + values',
    'bytes_per_element = 2 for FP16/BF16, 1 for INT8 (if supported for cache)',
    '```',
    '',
    'Operational takeaway: long prompts can destroy throughput even if the model is "fast" for short contexts.',
    '',
    '## Token Accounting',
    '',
    'Token accounting should be explicit and logged (see Chapter 18.1 and Chapter 17.4). Recommended counters:',
    '',
    '| Counter | Definition | Why it matters |',
    '|---|---|---|',
    '| prompt_tokens | tokens in system+developer+user+context | prefill cost, truncation risk |',
    '| completion_tokens | tokens generated | decode cost, verbosity control |',
    '| total_tokens | prompt_tokens + completion_tokens | cost, rate limits |',
    '| tool_tokens | tokens in tool outputs inserted into context | tool cost amplification |',
    '',
    'Common anti-pattern: tool output dumps (logs, huge JSON) directly into the prompt. Prefer summaries, structured fields, or retrieval over raw dumps (see Chapters 2 and 9).',
    '',
    '## Embedding Models',
    '',
    'Selection is mostly about domain match, latency, and vector dimensionality. Engineer-relevant tradeoffs:',
    '',
    '| Consideration | Lower is better? | Notes |',
    '|---|---|---|',
    '| Embedding dimension | Sometimes | Lower dims reduce storage and speed up ANN search, but can reduce recall |',
    '| Latency | Yes | Embeddings often sit on the critical path for RAG |',
    '| Domain fit | No | In-domain performance dominates generic marketing claims |',
    '| Normalization requirement | Depends | Cosine similarity usually assumes normalized vectors |',
    '',
    'Quick evaluation recipe (practical): build 50-200 real user queries, label 3-5 relevant docs per query, then compare recall@k and answer quality under the full pipeline (Chapters 14-16).',
    '',
    '## Vector Database Comparison',
    '',
    'This is a conceptual comparison. Real choices depend on operational constraints (multi-tenancy, compliance, managed vs self-hosted).',
    '',
    '| Capability | Why you care | Questions to ask |',
    '|---|---|---|',
    '| Filtering | Prevent wrong-domain hits | Can it filter efficiently by tenant, doc type, access policy? |',
    '| Hybrid search | Better exact-match retrieval | Can it combine BM25/keyword with vectors? |',
    '| Updates | Freshness and staleness | How fast do inserts become searchable? How are deletes handled? |',
    '| Consistency | Correctness under change | What are the consistency guarantees during index rebuilds? |',
    '| Cost model | Predictability | Storage cost (dims * count), read/write QPS pricing, egress |',
    '',
    '## Evaluation Metrics',
    '',
    'A small set of metrics covers most AI product work (see Chapters 15-16):',
    '',
    '| Metric | What it measures | Where it fails |',
    '|---|---|---|',
    '| Task success rate | Did the user goal get done? | Needs clear labeling; can hide partial errors |',
    '| Parse success rate | Can the output be consumed? | Can be high while semantics are wrong |',
    '| Grounding score | Are claims supported by sources? | Requires reliable attribution labeling |',
    '| Hallucination rate | Unsupported / fabricated content | Depends on definition and evaluators |',
    '| Latency p95/p99 | Tail performance | Needs per-stage breakdown |',
    '| Cost per success | Efficiency | Needs good accounting and attribution |',
    '',
    '## Common Failure Modes',
    '',
    'Use this as a debugging index (see Chapter 25 for deeper treatment).',
    '',
    '| Symptom | Likely cause | First fix to try |',
    '|---|---|---|',
    '| Malformed JSON | Weak output contract; sampling too random | Add schema validation + targeted retry; lower randomness |',
    '| Wrong tool args | Prompt injection; ambiguous schema | Tighten schema; server-side validation; confirmations |',
    '| Infinite agent loop | No termination conditions | Add step/tool/time budgets; enforce final-answer gate |',
    '| Confident but wrong | No grounding; stale retrieval | Force retrieval; add abstain; improve freshness |',
    '| Latency spikes | Long prompts; tool slowness | Token budgets; cache; timeouts; degrade |',
    '| Cross-tenant leak | Missing isolation | Partition indexes/caches/logs; enforce auth in retrieval |',
  ]),
};

const appendixEGlossary: DocPage = {
  slug: ['appendices', 'appendix-e-glossary'],
  title: 'Appendix E: Glossary',
  description: 'A student-friendly glossary of AI, infrastructure, and production engineering terms used throughout the handbook.',
  group: 'Appendices',
  toc: ['How To Read This Glossary', 'AI And Model Terms', 'Retrieval Terms', 'Reliability And Ops Terms', 'Security Terms'],
  body: md([
    '# Appendix E: Glossary',
    '',
    'Definitions here are optimized for engineering practice. When a term has multiple meanings in the wild, the definition matches how it is used in this handbook.',
    '',
    '## How To Read This Glossary',
    '',
    '- Many terms are connected. If you do not know one, scan nearby entries.',
    '- Cross references in parentheses point to where the concept is applied in chapters.',
    '',
    '## AI And Model Terms',
    '',
    '- **Activation**: The intermediate values produced inside a neural network while processing an input.',
    '- **Attention**: A mechanism that mixes information across tokens by computing learned weights (Appendix A; Chapters 3-4).',
    '- **Autoregressive decoding**: Generating output one token at a time, conditioning on all previous tokens (Chapter 3.4-3.5).',
    '- **Beam search**: A decoding strategy that keeps multiple partial hypotheses instead of sampling a single path (Chapter 3.6).',
    '- **Chat template**: A formatting convention that turns messages (system/developer/user) into a single token sequence.',
    '- **Completion**: The model-generated portion of output after the prompt.',
    '- **Context window**: The maximum token budget for prompt + completion (Appendix A; Chapter 2.5).',
    '- **Decode**: The phase where the model generates tokens; cost scales with output length (Chapter 3.4).',
    '- **Embedding**: A vector representation used for similarity search and retrieval (Chapter 12.3).',
    '- **Fine-tuning**: Updating model weights on new data so behavior changes persistently (Chapter 23.4).',
    '- **Function calling**: A model capability to emit structured tool calls that match a schema (Chapter 9).',
    '- **Generation**: The overall process of producing tokens during decode.',
    '- **Golden dataset**: A curated set of inputs and expected behavior used for regression testing (Chapter 15.1-15.3).',
    '- **Grammar-constrained generation**: Restricting outputs to a formal language to guarantee parseability (Chapter 8.3).',
    '- **Hallucination**: Output that is not supported by available evidence or is fabricated (Chapter 14.6; Chapter 25.1).',
    '- **Instruction hierarchy**: The rule that some messages (system/developer) should dominate others; implementations vary by platform.',
    '- **In-context learning**: Steering behavior using examples and instructions inside the prompt without changing weights (Chapter 23.2).',
    '- **KV cache**: Stored attention keys/values for past tokens to speed up decoding (Chapter 4).',
    '- **Latency**: End-to-end time to respond; usually measured at p50/p95/p99 (Chapters 17-19).',
    '- **Logits**: Unnormalized scores for next-token probabilities before softmax.',
    '- **LoRA / PEFT**: Parameter-efficient fine-tuning methods that adapt models with small additional weights (Chapter 23.5).',
    '- **Long context**: A model capability to condition on many tokens; quality and cost trade off (Chapter 2.8).',
    '- **Mixture of Experts (MoE)**: A model architecture that routes tokens through a subset of specialized experts (Appendix A).',
    '- **Model drift**: Output behavior changes over time due to model updates, data shifts, or environment changes (Chapter 17.7).',
    '- **Next-token prediction**: The training objective for many LLMs: predict the next token given previous tokens.',
    '- **Prefill**: Processing the prompt to build the initial internal state (Chapter 3.3).',
    '- **Prompt**: The full token sequence given to the model as input (system + user + context).',
    '- **Prompt drift**: Prompt effectiveness changes over time due to model changes, data shifts, or product changes (Chapter 17.8).',
    '- **Quantization**: Representing weights/activations with fewer bits to reduce memory and improve throughput (Chapter 7; Appendix D).',
    '- **Router**: A policy that chooses which model or pathway to use per request (Chapter 11).',
    '- **Sampling**: Choosing the next token stochastically from the probability distribution (Chapter 3.6; Appendix D).',
    '- **Schema validation**: Checking an output against a JSON schema or type contract (Chapter 8.4).',
    '- **Speculative decoding**: Using a draft model to propose tokens and a verifier to accept/reject, improving throughput (Chapter 6).',
    '- **Structured output**: Responses constrained to machine-parseable formats like JSON (Chapter 8).',
    '- **Temperature**: A knob controlling sampling randomness by scaling logits (Appendix D).',
    '- **Tool**: An external function the model can call, like search or database lookup (Chapter 9).',
    '- **Tool contract**: The schema + behavioral assumptions for a tool call (inputs, outputs, side effects) (Chapter 9.3).',
    '- **Token**: A discrete unit of text the model operates on; not the same as characters or words (Chapter 3.1).',
    '- **Top-k / Top-p**: Sampling filters that restrict candidate tokens (Appendix D).',
    '',
    '## Retrieval Terms',
    '',
    '- **ANN (Approximate Nearest Neighbor)**: Algorithms that find near vectors quickly without exact search.',
    '- **BM25**: A traditional keyword retrieval scoring method, often used in hybrid search (Chapter 12.6).',
    '- **Chunking**: Splitting documents into smaller pieces to embed and retrieve (Chapter 12.2).',
    '- **Citation / attribution**: Linking an answer claim to a retrieved source or tool result (Chapter 14.4-14.5).',
    '- **Context packing**: Selecting and ordering retrieved chunks to fit a token budget (Chapter 12.7).',
    '- **Cross-encoder reranker**: A model that scores query-document pairs jointly to improve relevance after initial retrieval (Chapter 13.1).',
    '- **Freshness**: How up-to-date the retrieval corpus and indexes are relative to the real world (Chapter 12.8).',
    '- **Grounding**: The extent to which answers are supported by provided evidence (Chapter 14.3).',
    '- **Hybrid search**: Combining semantic (vector) and lexical (keyword) search (Chapter 12.6).',
    '- **Query rewriting**: Transforming a user query to improve retrieval performance (Chapter 13).',
    '- **RAG (Retrieval-Augmented Generation)**: Using retrieval to supply external knowledge to the model (Chapter 12).',
    '- **Recall@k**: Whether a relevant document appears in the top k retrieval results.',
    '- **Vector database**: Storage + indexing system optimized for vector similarity search (Chapter 12.4).',
    '',
    '## Reliability And Ops Terms',
    '',
    '- **A/B test**: Online experiment comparing variants to measure impact (Chapter 16.4).',
    '- **Backoff**: Waiting longer between retries to reduce load and give systems time to recover (Chapter 19.1).',
    '- **Canary / shadow deployment**: Deploying a new version to limited traffic or in parallel for evaluation (Chapter 16.3).',
    '- **Circuit breaker**: Stops repeated calls to a failing dependency to prevent cascading failure (Chapter 19.3).',
    '- **Cost attribution**: Assigning costs (tokens, tool calls) to features/tenants for optimization (Chapter 18.2-18.5).',
    '- **Degradation mode**: A reduced-capability fallback when dependencies fail (Chapter 19.6).',
    '- **Error budget**: Allowed failure rate before you must prioritize reliability work (SRE concept; Chapter 19).',
    '- **Idempotency**: Repeating an operation produces the same result without duplicated side effects (Chapter 9.5).',
    '- **Load shedding**: Dropping work intentionally under overload to protect the system (Chapter 19.7).',
    '- **Observability**: The ability to understand internal state from outputs (logs, metrics, traces) (Chapter 17).',
    '- **p95 / p99 latency**: Tail latencies; critical for user experience and debugging (Chapter 17.5).',
    '- **Rate limiting**: Controlling request rate to protect systems and enforce quotas (Chapter 19.4).',
    '- **Regression**: A change that makes behavior worse versus a baseline (Chapters 15-16).',
    '- **Retry storm**: Many clients retry simultaneously, amplifying load and failures (Chapter 19.1).',
    '- **Span / trace**: Units in distributed tracing that represent operations and their timings (Chapter 17.2-17.3).',
    '- **Timeout**: A hard deadline after which an operation is aborted to bound latency (Chapter 19.2).',
    '',
    '## Security Terms',
    '',
    '- **Allowlist**: Explicit list of permitted actions/targets; safer than blocklists for tools.',
    '- **Data exfiltration**: Unauthorized data leaving a trust boundary (Chapter 21.2).',
    '- **Indirect prompt injection**: Malicious instructions embedded in retrieved content or web pages that the model reads (Chapter 20.6).',
    '- **Jailbreak**: Attempts to bypass safety rules or instruction hierarchy (Chapter 20.2).',
    '- **Least privilege**: Grant only the minimum permissions required to do a job (Chapter 21).',
    '- **PII**: Personally Identifiable Information; requires careful handling in prompts and logs (Chapter 21.4).',
    '- **Prompt injection**: Adversarial text that tries to override instructions or trigger unsafe tool behavior (Chapter 20.1, 20.5).',
    '- **Sandboxing**: Running tools in constrained environments to limit damage and data access (Chapter 21.6).',
    '- **Tenant isolation**: Preventing one customer\'s data from affecting or being visible to another (Chapter 22).',
  ]),
};

export const appendixPages: DocPage[] = [
  appendixACoreConcepts,
  appendixBEngineeringPatterns,
  appendixCChecklists,
  appendixDCheatsheets,
  appendixEGlossary,
];

